### ISSUE TITLE
Getting problems when installing face-recognition.js

### ISSUE THREAD

**Issue by UberFluff** [justadudewhohacks/face-recognition.js#1]
Hey, I wanted to try your library but I keep stumbling upon a node-gyp error saying that "C:\Microsoft.Cpp.Default.props" is missing.

**Comment by justadudewhohacks** [comment]
Hey, I guess you are installing this on windows. Have you installed the VS2017 build tools?

**Comment by UberFluff** [comment]
node v7.9.0
node-gyp v3.5.0
npm v4.2.0

After fiddling around I resolved this error but now I'm stuck with another one it says that facerec project needs v140 and installing only ms2015 tools doesn't work

**Comment by justadudewhohacks** [comment]
Hey looking at your path I guess you set `VCTargetsPath` to this path right? I think you shouldn't have to do that.

Regarding your error "C:\Microsoft.Cpp.Default.props is missing": I ran into this issue once, because I had an old msbuild.exe dangling in my path, coming from the .NET SDK or something. This caused the solution file to build created with v140  (VS 2015), rather then v141 (VS2017). Thus it threw the error trying to compile face-recognition.js with VS2017.

Can you open a terminal and type `where msbuild`, or `which msbuild` if you are using cmder or bash. You can also check your system path for any Visual Studio related paths to binaries, such as .NET SDK, to figure out, whether it has any conflicting msbuild.exes.

**Comment by UberFluff** [comment]
Yeah I did set the VCTargetsPath. I'll try upgrading npm and checking other msbuild this evening !

**Comment by UberFluff** [comment]
You were right, a weird .Net msbuild is called to build facerec but I can't uninstall it ... I've tried uninstalling it from the application list, removing it manually and I even tried [this](https://blogs.msdn.microsoft.com/astebner/2008/08/28/net-framework-cleanup-tool-users-guide/) without luck.

**Comment by justadudewhohacks** [comment]
For me simply removing the .NET sdk binaries from the system path did it. Have you checked whether it is in your system path or how did figure out, which msbuild.exe is used?

**Comment by UberFluff** [comment]
I can't find anything that can be linked to .Net see [here](https://imgur.com/gallery/ByAfW)

**Comment by justadudewhohacks** [comment]
Hmm maybe in the microsoft SQL server binn path?

Does `where msbuild` or `which msbuild` resolve anything for you?

**Comment by UberFluff** [comment]
Well where says : impossible to find any files for the specified models (it's a translation might not be exact)
and which isn't installed apparently

**Comment by justadudewhohacks** [comment]
Okay then msbuild is not found via system path, probably via registry then. 

So you are still confronted with the same error as above?

Did you `npm uninstall -g windows-build-tools` again? These are the VS2015 build tools, which wont work as the package has to be compiled with the VS2017 compiler.

Also in the node-gyp issue https://github.com/nodejs/node-gyp/issues/1144, it is being said, which SDK versions to install and which not to. Maybe this could also be useful to try.

**Comment by UberFluff** [comment]
I tried and tried and tried, anyway it's been a while since i've erased my hdd to go back to clean windows so I'll do this, this weekend and just install everything I want after that. Should work like a charm I hope.

**Comment by justadudewhohacks** [comment]
Bý the way did you also `npm config set msvs_version=2017`?

**Comment by UberFluff** [comment]
Okay I'm back, everything's clean, node-gyp starts the build and everything's working ! I just had an issue with node-gyp not seeing dlib so I just put the dlib folder in my path and it worked like a charm !
