### ISSUE TITLE
Logo Design Offer For face-recognition.js

### ISSUE THREAD

**Issue by iqbalhood** [justadudewhohacks/face-recognition.js#101]
Hello Sir. I'm a UI/UX and Graphics Designer. 
I have read the article you created in the medium, I am interested to create a logo for this project.
Would you mind if I propose logo for your application as my Open Source Contribution?

Thanks before.
Regards,
@iqbalhood

**Comment by justadudewhohacks** [comment]
That sounds awesome, thank you. I am looking forward to see it ;)

**Comment by iqbalhood** [comment]
Hello sir,
These are my logo proposal for your project. If there any revision, please just tell it.
Version 1

![screen shot 2018-07-02 at 23 26 48](https://user-images.githubusercontent.com/1563756/42175428-91e2496c-7e4f-11e8-82e7-cbcb569e7a37.png)

Version 2
![screen shot 2018-07-02 at 23 27 16](https://user-images.githubusercontent.com/1563756/42175442-a0b69a24-7e4f-11e8-9e3d-161d954e3baa.png)


Version 3
![screen shot 2018-07-02 at 23 25 35](https://user-images.githubusercontent.com/1563756/42175472-b2cab376-7e4f-11e8-8b4c-940bc65922ff.png)

**Comment by Zwimber** [comment]
Is it like a vote? #TeamVersion1

**Comment by justadudewhohacks** [comment]
Thanks a lot for creating the proposals! Personally I also like version 1 the most. Which one would you go for @iqbalhood?

**Comment by iqbalhood** [comment]
I think that is a great choice. If you don't mind. I will send the editable file to you and make pull request in github to change the readme[.]md  file.

**Comment by justadudewhohacks** [comment]
Sure! Go ahead.

**Comment by iqbalhood** [comment]
hello sir, I have made a pull request for the addition of the logo and modification of the readme.md file here.
https://github.com/justadudewhohacks/face-recognition.js/pull/106

If you need the editable file, you can check it here.
https://drive.google.com/drive/folders/1NQDvVGs7qpJnpHUfMlZVZWH2lFaP9YZt?usp=sharing

**Comment by justadudewhohacks** [comment]
Awesome, thanks for your work!
