### ISSUE TITLE
Can't build package with openblas support on windows

### ISSUE THREAD

**Issue by thexiroy** [justadudewhohacks/face-recognition.js#104]
I compiled openblas manually and set the system environment variables to the directory containing libopenblas.lib and libopenblas.dll. However the package does not build with openblas.

Looking in the console I can see that it found the libopenblas.lib but right after it displays the following message:
-- Could NOT find BLAS (missing: BLAS_LIBRARIES)
-- LAPACK requires BLAS

Did I maybe forget any steps or did something change? Not sure what I am doing wrong.

**Comment by thexiroy** [comment]
![openblas_problem](https://user-images.githubusercontent.com/12149840/42277948-655a9958-7f99-11e8-9de2-a92e48a21827.png)

**Comment by thexiroy** [comment]
![openblas_lib](https://user-images.githubusercontent.com/12149840/42278026-b243f264-7f99-11e8-84f0-1209a7abc6bf.png)

**Comment by justadudewhohacks** [comment]
Hmm looks good to me. Instead of using dlib-build, you could also try building dlib on your own using cmake, maybe that helps. Otherwise I would ask in the dlib repo, how to properly link dlib with openblas on windows.

**Comment by thexiroy** [comment]
Followed instructions on the OpenBlas wiki and it can now properly detect and load openblas when I install face-recognition.
But I get the following error when I try to run with node: The specified module could not be found.
![facerec_node_problem](https://user-images.githubusercontent.com/12149840/42317888-bce0848a-804d-11e8-83b4-93d3c89185b6.png)
 
Looked into the folders and the facerec.node is there. Any insight what could be wrong?

**Comment by justadudewhohacks** [comment]
Nice, well node was not able to load some dll, I assume it's libopenblas.dll. Are you sure the path to libopenblas.dll is in your system path?

**Comment by thexiroy** [comment]
![openblas_systemenv](https://user-images.githubusercontent.com/12149840/42321068-ddc92d46-8057-11e8-8a25-2d00683bdd41.png)
Seems fine to me? 

I am going to rebuild openblas at home and I will also try with another windows computer, just to be sure. If it's still not fixed, you can close this issue since I don't want to waste your time. 

Thanks for the help so far.

**Comment by justadudewhohacks** [comment]
Is this a screenshot of your path variable? Usually you don't put the fill filepath to runtime files in there, but rather the path to the directory contraining the runtime libraries, e.g. `.../openblas` instead of `.../openblas/openblas.dll`.

**Comment by thexiroy** [comment]
Indeed, I also tried with setting the path to the directory I get the same result. When I do not provide a openblas.dll node-recognition package shows that it cannot find openblas. I think the problem lies in compiling the openblas.dll, I must have done something wrong which hasn't really anything to do with this package.

**Comment by justadudewhohacks** [comment]
Hmm, by the way, you can use dependency walker on the .node file in the build directory of face-recognition.js to see which dlls are missing.

**Comment by justadudewhohacks** [comment]
Python is required for node-gyp. You only need to compile dlib with openblas, as you already did. I would recommend you to use dependency walker to figure out, which runtime dependencies are missing, before making wild guesses, what could have possibly gone wrong.

**Comment by thexiroy** [comment]
![openblas_dependencywalker](https://user-images.githubusercontent.com/12149840/42372476-90139f1c-8112-11e8-8a26-f3f6fde9156f.png)
I have gone through all the dependencies, there is an error opening OPENBLAS.DLL.
To build openblas I used section _1. Native MSCV ABI_ from https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio

**Comment by thexiroy** [comment]
When opening the openblas dll with dependency walker I found that it's missing FLANG.DLL, I will look into that.

**Comment by thexiroy** [comment]
I have figured out the issue. It turned out that the openblas.dll couldn't be found even when setting it's location in the system PATH. Using anaconda (which I used to build openblas) seems to make it work.

**Comment by rafaP** [comment]
I'm trying to build the files libopenblas.lib and libopenblas.dll, but i got an error:  FAILED: cmTC_b511b.exe
I'm following the https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio chapter 1. and i'm at this command: cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DBUILD_WITHOUT_LAPACK=no -DNOFORTRAN=0 -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Release

**Comment by thexiroy** [comment]
@rafaP Did you use the latest release build of OpenBLAS from here? https://github.com/xianyi/OpenBLAS/releases

For me it works fine (even on different computers).

**Comment by rafaP** [comment]
oh, i don't get it from there.
gonna try to build it from there

**Comment by rafaP** [comment]
It build successfully, but i don't have the files libopenblas.lib and libopenblas.dll

**Comment by thexiroy** [comment]
Ok tell me when you get it working so that I can close this issue :)

**Comment by rafaP** [comment]
it compile, but i only got the openblas.dll

![image](https://user-images.githubusercontent.com/3018248/42634224-8b722196-85da-11e8-96c8-0f7fbbd00567.png)

**Comment by thexiroy** [comment]
This is more an OpenBlas issue so I am going ahead and close this issue. You could make an issue on their github repository.

**Comment by rafaP** [comment]
Sorry to come here again, but what have you done to find the openblas.dll with anaconda so it works with the face-recognition?
