### ISSUE TITLE
Group unrecognized faces by similarities

### ISSUE THREAD

**Issue by edoardoo** [justadudewhohacks/face-recognition.js#107]
Hi,
I was wondering if it's possible to use the face recognition and face detection features to group unknown similar faces. 
Concept can be described as: I don't know this guy but is similar to this other guy of which I don't know the name, yet.
This feature would be extremely helpful for labeling. 

Thanks

**Comment by justadudewhohacks** [comment]
Of course it is possible. Simply compute the face descriptors of the unkown persons and compare them by euclidean distance, just the same, as the FaceRecognizer does.

**Comment by edoardoo** [comment]
I see, it was much easier than I thought. 
Thank you for the answer and this work.
Have a nice day.
