### ISSUE TITLE
Face-recognition don't work after installing Openblas

### ISSUE THREAD

**Issue by rafaP** [justadudewhohacks/face-recognition.js#112]
The face recognition module is not working after building the Openblas and include it in the environment variables.

I reeinstall the module but it gives me this error when i try to run my code:

module.js:681
return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\.......\Desktop\node\node_modules\face-recognition\build\Release\facerec.node
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\......\Desktop\node\node_modules\face-recognition\lib\fr.js:6:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by rafaP** [comment]
executing: if not exist dlib mkdir dlib
executing: if not exist build mkdir build
executing: if exist dlib rd /s /q dlib
spawning: git [ 'clone',
  '--progress',
  'https://github.com/davisking/dlib.git' ]
Cloning into 'dlib'...
remote: Counting objects: 46538, done.
remote: Compressing objects: 100% (110/110), done.
remote: Total 46538 (delta 105), reused 137 (delta 83), pack-reused 46343
Receiving objects: 100% (46538/46538), 21.80 MiB | 1.57 MiB/s, done.
Resolving deltas: 100% (32685/32685), done.
Checking out files: 100% (2137/2137), done.
spawning: git [ 'checkout', 'tags/v19.8', '-b', 'v19.8' ]
Checking out files: 100% (586/586), done.
Switched to a new branch 'v19.8'
spawning: cmake [ 'C:\\Users\\rafael.pereira\\Desktop\\node\\node_modules\\dlib-build\\dlib\\dlib',
  '-G',
  'Visual Studio 15 2017 Win64',
  '-DDLIB_USE_BLAS=ON',
  '-DBLAS_Accelerate_LIBRARY=C:\\Users\\rafael.pereira\\Desktop\\node\\openblas\\libopenblas.lib' ]
-- The C compiler identification is MSVC 19.14.26433.0
-- The CXX compiler identification is MSVC 19.14.26433.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Enabling SSE2 instructions
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Found BLAS: C:/Users/rafael.pereira/Desktop/node/openblas/libopenblas.lib
-- Looking for sgesv
-- Looking for sgesv - found
-- Looking for sgesv_
-- Looking for sgesv_ - found
CUDA_TOOLKIT_ROOT_DIR not found or specified

**Comment by thexiroy** [comment]
Had the same, start Anaconda and type: `Node faceRecognition.js` where faceRecognition.js is your javascript file that you try to run. 

It seems something goes wrong with the environment variables, haven't found a real solution yet since I am focusing on other stuff at the moment.

Hope this helps you a little and please share a solution if you have found one :)

**Comment by rafaP** [comment]
Ok. Thank you for the answer.

If i find other solution i will write here.

**Comment by rafaP** [comment]
It gives the same error.
can't find the module.

**Comment by thexiroy** [comment]
Copy the Openblas files to the same directory as your javascript file that you are trying to run. And then try again, that worked for me.

**Comment by rafaP** [comment]
But you build the dlib too?

**Comment by rafaP** [comment]
Me too, But i still get the same error.

(base) C:\Users\...\Desktop\node> Node app.js
module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\.....\Desktop\node\node_modules\face-recognition\build\Release\facerec.node
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\........\Desktop\node\node_modules\face-recognition\lib\fr.js:6:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

**Comment by thexiroy** [comment]
Try to copy the Openblas files to where the facerec.node file is located (`node_modules\face-recognition\build\Release\facerec.node`. I will reinstall face-recogntion.js on my computer and see if I get the same problem.

**Comment by rafaP** [comment]
Or maybe my Openflas files are wrong.

**Comment by thexiroy** [comment]
I think not, I have the same error with `facerec.node`. I used `1. Native (MSVC) ABI` from: [https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio](url)

For whatever reason it doesn't build with openblad right now, I will try some things tomorrow since I am heading out for today.

Could you maybe provide a screenshot of your environment variables for Openblas, I will then look at them tomorrow.

**Comment by rafaP** [comment]
I only have this:

![image](https://user-images.githubusercontent.com/3018248/42890038-c0245eae-8aa3-11e8-822f-6373c8e3902c.png)

**Comment by rafaP** [comment]
Yes. But now i get a error of dependecy of Flang.dll and Flangrti.dll
When i try to run the face-recognition js with the Openblas

![image](https://user-images.githubusercontent.com/3018248/42930973-5a36b27a-8b36-11e8-9cb2-ab2607a95e89.png)

**Comment by thexiroy** [comment]
I think I had the same errors, I got my face-recognition just working with openblas in  **anaconda**. Using dependency walker in a sec, I will let you know what I can find.

**Comment by rafaP** [comment]
Ok, thank you for all the help and effort you have been doing to find a fix for this.

**Comment by justadudewhohacks** [comment]
Hmm I am not sure what has to be done, when you compile openblas using flang, apparently you need to also provide runtimes for flang then. I simply compiled it using Visual Studio + cmake. This apparently requires perl though to compile it.

**Comment by rafaP** [comment]
I have tried to add the flan dlls, but it doesn't work, it keep asking for more files if i use the dependency walker on the .node file.

**Comment by rafaP** [comment]
maybe we need to compile with Visual studio and cmake

**Comment by rafaP** [comment]
It works if we add this files in the release folder:

![image](https://user-images.githubusercontent.com/3018248/42945758-17d85692-8b61-11e8-87be-ad7e05e6251b.png)

**Comment by rafaP** [comment]
Yes. 500ms to 700ms
