### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by jinusean** [justadudewhohacks/face-recognition.js#115]
I'm getting a `Segmentation fault: 11` when I'm following the example:
```
const win = new fr.ImageWindow()
win.setImage(img)
win.renderFaceDetections(shapes)
win.addOverlay(rect)
``` 

I've isolated the problematic function to `win.renderFaceDetections(shapes)` and the code runs fine if I remove that line. I've tried uninstalled ll the dependencies and reinstalling but still getting the same error. 

The code works fine on my mac Sierra machine, but not on a mac with High Sierra.
Any help will be appreciated.

**Comment by Erozionn** [comment]
How did you end up fixing this?
