### ISSUE TITLE
api details for face-recognition.js

### ISSUE THREAD

**Issue by tanmaypatil** [justadudewhohacks/face-recognition.js#12]
Hi Vincent ,

Facing issue during running some of the sample code in the page https://github.com/justadudewhohacks/face-recognition.js .
api details for accessing imageWindow object is not clear to me .
here addOverlay method is taking rectangle  object . however its type is not known .
I believe these are js api are wrapper over dlib library . 
Please correct me in case my understanding of this infrastructure is wrong .  

const win = new fr.ImageWindow()
// display image
win.setImage(image)
// drawing the rectangle into the displayed image
**win.addOverlay(rectangle)**
// pause program until key pressed
fr.hitEnterToContinue()

**Comment by justadudewhohacks** [comment]
Hi,

rectangle is of type fr.Rect. Beware there is also the MmodRect class. Rect is what what is returned by the FrontalFaceDetector directly, MmodRect is returned by the FaceDetector or more precisely the face detection net wrapper class.

MmodRect has the properties rect of type Rect and confidence. So in case you use the FaceDetector you would retrieve the rectangle by mmodRect.rect. Also see the examples.

**Comment by justadudewhohacks** [comment]
Closing, if there are still questions remaining, feel free to reopen.
