### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by Chuiantw1212** [justadudewhohacks/face-recognition.js#122]
![error](https://user-images.githubusercontent.com/10844438/45287413-cbeec480-b51a-11e8-8b6d-af8a254bc28d.png)

dlib is built with no erros.
Could not figure out how to resolve this unexpected syntax error.
Is this something about Python that went wrong?

**Comment by justadudewhohacks** [comment]
Hmm maybe an issue with node-gyp + python 3.7. You could try to use python 3.6 instead.

**Comment by Chuiantw1212** [comment]
I failed to reproduce this situation.
Maybe that was something relative to my poor python environment setup. Which was a result of cutting and pasting multiple solutions of version conflicts (without any vital organs processing at the time).
After a system reinstallation, now I'm using python 3.7 and it works well.

**Comment by Chuiantw1212** [comment]
New information here.
Python 3.7 on **Mac** works fine. It was a brand new re-installation which is how I got the conclusion that the "Invalid Syntax" error was a result of messy environment setup.

Now i just had the same Invalid Syntax error with a re-installed **Windows**.  And yes, it was something about python. It seems python 3.7 + windows OS are the cause.
