### ISSUE TITLE
XIO:  fatal IO error 35 (Resource temporarily unavailable) on X server "/private/tmp/com.apple.launchd.zsmysouT4S/org.macosforge.xquartz:0"

### ISSUE THREAD

**Issue by ThantYarZarHein** [justadudewhohacks/face-recognition.js#128]
Hi,

I don't know How to resolve this problem.I did find that error and also no idea about that.Could anyone help me with this problem, pls.

```
const path = require('path')
const cv = require('opencv4nodejs')
const fr = require('face-recognition').withCv(cv)

const cvMat = cv.imread('img1.jpeg');
const cvImg = fr.CvImage(cvMat);

const win = new fr.ImageWindow()
win.setImage(cvImg)
fr.hitEnterToContinue()
```

> XIO:  fatal IO error 35 (Resource temporarily unavailable) on X server "/private/tmp/com.apple.launchd.zsmysouT4S/org.macosforge.xquartz:0"
>       after 260 requests (260 known processed) with 0 events remaining.

**Comment by Chuiantw1212** [comment]
I'm confused. Which line went wrong?
