### ISSUE TITLE
how to extact face coordinates for each face

### ISSUE THREAD

**Issue by vijaysagi** [justadudewhohacks/face-recognition.js#14]
Hi,
Currently we are leveraging on python to extract face coordinates of each face to undergo face recognition.

We would like to replace the python module (https://github.com/davisking/dlib) with face-recognition.js

Ex: existing python code
img='test.jpg'
facerec = dlib.face_recognition_model_v1('dlib_face_recognition_resnet_model_v1.dat')
face_descriptor = facerec.compute_face_descriptor(img, shape)
we are storing face_descriptor values in the DB and processing for face recognition.

Please suggest using face-recognition.js how can we extract face descriptor values.

Thanks
vijay

**Comment by justadudewhohacks** [comment]
You can get the face descriptors by:

```
const models = require('face-recognition-models')
const net = new fr.FaceRecognizerNet(models.faceRecognitionModel)
const descriptor = net.computeFaceDescriptor(faceImg)
```

You can also see the js code under /lib to see how to use the API directly, which I wrapped in FaceDetector and FaceRecognizer for example.

If you only need the face locations you can also see the locateFaces example.

**Comment by justadudewhohacks** [comment]
1. The Array class has a `getData()` method. Assuming you have an Array `faceDescriptor`:
``` javascript
const faceDescriptorArray = faceDescriptor.getData()
```

2. Simply save them as JSON? :
``` javascript
// save
const fs = require('fs')
fs.writeFileSync( 'descriptor.json', JSON.stringify(faceDescriptorArray) )

// load
const faceDescriptorArray = require('descriptor.json')
const faceDescriptor = new fr.Array(faceDescriptorArray)
```

**Comment by vijaysagi** [comment]
awesome thank u so much
