### ISSUE TITLE
how to compare face descriptor values for face recognition

### ISSUE THREAD

**Issue by AvinashOB** [justadudewhohacks/face-recognition.js#15]
Hi,

We are able to extract face descriptor values(128 parameters) from the image and store it in JSON file.

While face recognition, we need to extract face coordinates from the json file and compare it with  the existing face coordinates.

I could not find the relavant method how to compare two face coordinates for face recognition.

Please suggest the way forward

Thank you.

**Comment by AvinashOB** [comment]
Maybe  the heading has to be changed to  ****

**Comment by justadudewhohacks** [comment]
Hey,

The way I did it in the FaceRecognizer wrapper class is to compute the euclidean distance of an input descriptor to all face descriptors of a class and compute a mean value:
``` javascript
/* compute the mean value of the euclidean distances of the input descriptor */
/* to each of the face descriptors, which the recognizer has been trained on, */
/* this is used as the metric to judge how similar the faces are to the training data*/
function computeMeanDistance(descriptors, inputDescriptor) {
  return round(
    descriptors
      .map(d => fr.distance(d, inputDescriptor))
      .reduce((d1, d2) => d1 + d2, 0)
        / descriptors.length || 1
  )
}
```

**Comment by justadudewhohacks** [comment]
Closing, if there are still questions remaining, feel free to reopen.
