### ISSUE TITLE
ERRO WHEN I TRY RUN NPM INSTALL FACE-RECOGNITION

### ISSUE THREAD

**Issue by thqueiroz** [justadudewhohacks/face-recognition.js#157]
Im having a problem when i try run npm install face- recognition. 
I need to help!

5 warnings and 10 errors generated.
make: *** [Release/obj.target/facerec/cc/index.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/Cellar/node/12.9.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/thqueiroz/Documents/facerecognition-node/node_modules/face-recognition
gyp ERR! node -v v12.9.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN facerecognition-node@1.0.0 No description
npm WARN facerecognition-node@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! face-recognition@0.9.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the face-recognition@0.9.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by MukeshKalaga** [comment]
Did it solve?
or
What alternative did u use?

**Comment by thqueiroz** [comment]
> Did it solve?
> or
> What alternative did u use?

I used face-api.js

**Comment by Wasi-Ayub** [comment]
> -api.js

How it's work with nodeJS?

**Comment by Wasi-Ayub** [comment]
Yeah i fixed it,
firstly "Remove spaces in folder name in your directory"
Run these command in Ubuntu step by step,
> sudo apt-get -y install cmake
> which cmake
/usr/bin/cmake
> cmake --version
cmake version 2.8.12.2

> sudo apt-get -y install cmake-qt-gui
> which cmake-gui
/usr/bin/cmake-gui
> cmake-gui --version
cmake version 2.8.12.2

> wget https://cmake.org/files/v3.4/cmake-3.4.1-Linux-x86_64.tar.gz
> tar xf cmake-3.4.1-Linux-x86_64.tar.gz
> export PATH="`pwd`/cmake-3.4.1-Linux-x86_64/bin:$PATH" # save it in .bashrc if needed
> which cmake
/.../cmake-3.4.1-Linux-x86_64/bin/cmake
> which cmake-gui
/.../cmake-3.4.1-Linux-x86_64/bin/cmake-gui

then,
npm install face-recognition

**Comment by thqueiroz** [comment]
fixed by @Muhammad-Wasi
