### ISSUE TITLE
CMake is pretending there is a "project(Project)" command on the first   line. CMake Error in CMakeLists.txt:   Generator      Visual Studio 15 2017 Win64    could not find any instance of Visual Studio.

### ISSUE THREAD

**Issue by ann1111** [justadudewhohacks/face-recognition.js#159]
D:\DavidHRMS>npm install face-recognition

> dlib-build@0.1.1 install D:\DavidHRMS\node_modules\dlib-build
> node ./install.js

executing: git --version
executing: cmake --version
find vs2017 via powershell: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe [
  '-ExecutionPolicy',
  'Unrestricted',
  '-Command',
  "&{Add-Type -Path 'D:\\DavidHRMS\\node_modules\\dlib-build\\lib\\Find-VS2017.cs'; [VisualStudioConfiguration.Main]::Query()}"
]
executing: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe [
  '-ExecutionPolicy',
  'Unrestricted',
  '-Command',
  "&{Add-Type -Path 'D:\\DavidHRMS\\node_modules\\dlib-build\\lib\\Find-VS2017.cs'; [VisualStudioConfiguration.Main]::Query()}"
]
find vs2017:  {"log":"Found installation at: C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\n  - Found Microsoft.VisualStudio.Component.Windows10SDK.18362\n  - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64\n  - Found Microsoft.VisualStudio.VC.MSBuild.Base\n  - Using this installation with Windows 10 SDK","path":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community","sdk":"10.0.18362.0"}

found vs2017
path C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
sdk 10.0.18362.0
executing: if not exist dlib mkdir dlib
executing: if not exist build mkdir build
executing: if exist dlib rd /s /q dlib
spawning: git [ 'clone', '--progress', 'https://github.com/davisking/dlib.git' ]
Cloning into 'dlib'...
remote: Enumerating objects: 48063, done.
remote: Total 48063 (delta 0), reused 0 (delta 0), pack-reused 48063 eceiving objects: 100% (48063/48063), 22.14 MiB | 2.24 MiB/s
Receiving objects: 100% (48063/48063), 22.73 MiB | 2.00 MiB/s, done.
Resolving deltas: 100% (33918/33918), done.
Updating files: 100% (2172/2172), done.
spawning: git [ 'checkout', 'tags/v19.8', '-b', 'v19.8' ]
Switched to a new branch 'v19.8'
spawning: cmake [
  'D:\\DavidHRMS\\node_modules\\dlib-build\\dlib\\dlib',
  '-G',
  'Visual Studio 15 2017 Win64'
]
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error in CMakeLists.txt:
  Generator

    Visual Studio 15 2017 Win64

  could not find any instance of Visual Studio.

-- Configuring incomplete, errors occurred!
See also "D:/DavidHRMS/node_modules/dlib-build/dlib/build/CMakeFiles/CMakeOutput.log".
child process exited with code 1
npm WARN @angular/common@8.0.0 requires a peer of rxjs@^6.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/core@8.0.0 requires a peer of rxjs@^6.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@8.0.0 requires a peer of rxjs@^6.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@8.0.0-beta.10 requires a peer of @angular/core@8.0.0-beta.10+1.sha-a28b3e3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@8.0.0-beta.10 requires a peer of @angular/platform-browser@8.0.0-beta.10+1.sha-a28b3e3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/router@8.0.0 requires a peer of rxjs@^6.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN kinvey-nativescript-sdk@4.2.1 requires a peer of @angular/core@~7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN kinvey-nativescript-sdk@4.2.1 requires a peer of nativescript-plugin-firebase@~8.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN DavidHRMSCloud@3.0.0 No repository field.
npm WARN DavidHRMSCloud@3.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dlib-build@0.1.1 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dlib-build@0.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2020-05-30T06_36_24_702Z-debug.log

**Comment by ann1111** [comment]
HI  @justadudewhohacks  can you please help me regarding this  1 sec VS installed also cmake as well but after it shows like this

**Comment by ann1111** [comment]
resolved

**Comment by 0xCA** [comment]
> 
> 
> resolved

HOW
