### ISSUE TITLE
Install issue MacOS (High Sierra)

### ISSUE THREAD

**Issue by davidloiret** [justadudewhohacks/face-recognition.js#2]
Hello thanks for your work.
However I have some issue to install via the `npm install face-recognition`.
I am getting the following error:
`CMake Error: Could not create named generator Visual Studio 15 2017 Win64`

I believe it is due to the latest OS based code of https://github.com/justadudewhohacks/npm-dlib-build/commit/b8c17de5e6a0c38e9eed1eee2f85c6f3b0b55d1e not published on npm.

OS: MacOS High Sierra
npm version: 5.6.0
node version: 8.9.4

Can't wait to test this lib, thanks!

**Comment by justadudewhohacks** [comment]
Oh damn you are right... I published it now. Thanks for reporting this!

**Comment by davidloiret** [comment]
Thanks. And point to v0.0.3 in package.json of this repo please.

**Comment by justadudewhohacks** [comment]
Just noticed :D

**Comment by davidloiret** [comment]
Yep I run on the following issue, I guess it's the same you're mentioning

```
> node-gyp rebuild

  CXX(target) Release/obj.target/facerec/cc/index.o
In file included from ../cc/index.cc:9:
../cc/Array.h:16:25: error: call to member function 'Set' is ambiguous
                info.GetReturnValue().Set(Converter::unwrap(info.This()).size());
                ~~~~~~~~~~~~~~~~~~~~~~^~~
../../nan/nan_callbacks_12_inl.h:46:15: note: candidate function
  inline void Set(bool value) {
              ^
../../nan/nan_callbacks_12_inl.h:51:15: note: candidate function
  inline void Set(double i) {
              ^
../../nan/nan_callbacks_12_inl.h:56:15: note: candidate function
  inline void Set(int32_t i) {
              ^
../../nan/nan_callbacks_12_inl.h:61:15: note: candidate function
  inline void Set(uint32_t i) {
              ^
../../nan/nan_callbacks_12_inl.h:27:37: note: candidate template ignored: could not match 'Local<type-parameter-0-0>'
      against 'long'
  template <typename S> inline void Set(const v8::Local<S> &handle) {
                                    ^
../../nan/nan_callbacks_12_inl.h:32:37: note: candidate template ignored: could not match 'Global<type-parameter-0-0>'
      against 'long'
  template <typename S> inline void Set(const Global<S> &handle) {
                                    ^
../../nan/nan_callbacks_12_inl.h:89:15: note: candidate template ignored: could not match 'S *' against 'long'
  inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
              ^
1 error generated.
make: *** [Release/obj.target/facerec/cc/index.o] Error 1
```

**Comment by davidloiret** [comment]
So I believe the correct way to handle that is:
```
			['OS=="mac"', {
				'xcode_settings': {
					'GCC_ENABLE_CPP_RTTI': 'YES'
				}
			}],
			[ 'OS=="linux" or OS=="freebsd" or OS=="openbsd" or OS=="solaris"',
				{
					'cflags_cc!': ['-fno-rtti'],
					'cflags_cc+': ['-frtti'],
				}
			],
```

But now I have another error: `clang: error: no such file or directory: '/Users/davidloiret/Downloads/face-recognition.js-master/node_modules/dlib-build/dlib/build/dlib/libdlib.so.19.8.0'`

**Comment by justadudewhohacks** [comment]
Sorry for delay issues should be fixed now. I also exported the dynamic lib (.so, on mac it's .dylib actually) instead of .a. Should be resolved now.

**Comment by davidloiret** [comment]
No problem, no it's not sufficient I am getting 
`cannot use dynamic_cast with -fno-rtti` 
Works fine with `'GCC_ENABLE_CPP_RTTI': 'YES'`

**Comment by justadudewhohacks** [comment]
Okay thanks. I will add this.

**Comment by davidloiret** [comment]
Thanks

**Comment by justadudewhohacks** [comment]
So I finally got the examples running on linux. Turns out I also had to link libx11 for the dlib gui and libpng.

I have published the most recent version and updated the install instructions. On mac you will probably also have to brew install libx11 if its possible. On linux it's `sudo apt-get install libx11-dev`.

Sorry for all the inconvenience.

**Comment by davidloiret** [comment]
Some progress but now failing with `ld: library not found for -lX11`
I have xQuartz installed

**Comment by justadudewhohacks** [comment]
Hmm, I have added `-lX11` to the linker flags in face-recognition/lib/libs.js `console.log('-lX11')`. Maybe it works if you simply link xQuartz instead?

**Comment by davidloiret** [comment]
If it helps
```
dl$ locate libX11
/opt/X11/lib/libX11-xcb.1.dylib
/opt/X11/lib/libX11-xcb.dylib
/opt/X11/lib/libX11.6.dylib
/opt/X11/lib/libX11.dylib
```

**Comment by justadudewhohacks** [comment]
Maybe any of these:
`-L/opt/X11`
`-L/opt/X11/lib/libX11`

Also found the suggestion `sudo ln -s /opt/X11 /usr/X11` here https://tex.stackexchange.com/questions/208001/cant-compile-image-after-upgrading-to-os-x-yosemite.

I will setup travis CI tomorrow, to know for sure whats going on with OSX. Currently I do not have a MAC VM to test it myself.

**Comment by davidloiret** [comment]
So I finally change to  `console.log('-lX11')` `console.log('-L/usr/X11/lib -lX11')`
But the examples are not working:
```
const img = fr.loadImage('./data/Lenna.png')
               ^

Error: load_image failed to open file: std::exception
    at Object.<anonymous> (/Users/davidloiret/Downloads/face-recognition.js-master/examples/detectFaceLandmarks.js:10:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by davidloiret** [comment]
So I finally change to `console.log('-lX11')` `console.log('-L/usr/X11/lib -lX11')` and it works.
But the examples are not working:

```const img = fr.loadImage('./data/Lenna.png')
               ^

Error: load_image failed to open file: std::exception
    at Object.<anonymous> (/Users/davidloiret/Downloads/face-recognition.js-master/examples/detectFaceLandmarks.js:10:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3```

**Comment by justadudewhohacks** [comment]
Hmm maybe upgrading libpng to the latest version helps?

**Comment by davidloiret** [comment]
Nope, another issue I am facing in the `faceRecognition1.js` example:
```
dyld: lazy symbol binding failed: Symbol not found: _cblas_sgemm
  Referenced from: /Users/davidloiret/Downloads/face-recognition.js-master/build/Release/facerec.node
  Expected in: flat namespace
```

**Comment by justadudewhohacks** [comment]
Newest version should run on OSX now. I made the mistake of linking dlib statically, thus probably the missing dependancy of libblas.

**Comment by davidloiret** [comment]
Works like a charm, thanks!
