### ISSUE TITLE
Unable to detect faces in an image having dimensions 80 X 107

### ISSUE THREAD

**Issue by pratikgchaudhari** [justadudewhohacks/face-recognition.js#22]
Hi,
I was wondering if there's any restriction on the minimum dimensions of an image in order to detect faces in it. Currently I am trying detect face in a person's image whose dimensions are 80 X 107.
The `detector.detectFaces()` method returns an empty array.

**Comment by justadudewhohacks** [comment]
Yes there are restrictions. You can try to scale up the image size using fr.resizeImage. However the smaller the faces the noisier the output for face recognition will be.

The minimum size the face recognizer will accept is somewhere around 105x105 anyways. I usually use 150x150 sized face Images which provides better results.

**Comment by pratikgchaudhari** [comment]
`fr.resizeImage()` worked like a charm.
Thanks!
