### ISSUE TITLE
Distance is growing as I add more faces 

### ISSUE THREAD

**Issue by bobmoff** [justadudewhohacks/face-recognition.js#29]
Hi again :)

I am a little confused by the results that I am getting. The more faces I add to a class, the longer the distance get.

1. If I add just two faces, and use one the those faces to make a prediction. The distance is non-zero. As I understand it the distance whould be 0, as that exact face exists in one of the classes. Instead I get like 0.7 for each of the photos.

2. As I continue adding faces to these two classes and keep predicting some other faces that are not added in any class, the distances keep growing the more faces I add.

I am not sure how to interpret these results. 

I am trying to build a photo service where users will add faces to people and the system should offer suggestions of other photos in their collection that most likely also is these people, but as the distances grow I am not sure how to handle the confidence score of the predictions.

My assumptions was that as I add more faces, the distances would get reduced as the recognizer gets more data and can make more accurate predictions.

Any tips?

**Comment by justadudewhohacks** [comment]
Hi,

The distance is just the mean of all euclidean distances from an input face descriptor, all other face descriptors of a class. Thus the distance of a face descriptor to itself is 0.

If you add more training faces, which seem to be more unsimilar, the average distance for a class to an input descriptor will tend to grow.

If you use 150x150 sized faces usually a distance lower then 0.6 seems to be a good threshold, to indicate a match. I found using lower sizes such as 105x105 also requires to increase the threshold to like 0.8. Also make sure not to mix up face images of different sizes.

**Comment by bobmoff** [comment]
Thanks as usual for lightning fast responses, really appreciate it.

I think I have found a bug in your makeComputeMeanDistance function. It returns 1 instead of 0 when there is only one face added to a class, and if I use the predictBest function, it will actually return the OTHER class as it has a lower distance. If the result of the reduce function becomes 0 then the OR ( || ) operation uses the default 1 as return value. Guess you just need to put braces around the (descriptors.length || 1) to make sure it gets evaluated separately. I guess your intention was to not divide by zero ? I have created a PR, but I am not sure if it will mess up anything else.

**Comment by justadudewhohacks** [comment]
Yep you are right, forgot the braces there and didn't want to divide by 0. Thanks for fixing this :D. Did that actually fix the problem you described?

**Comment by bobmoff** [comment]
Ok, cool.

I guess there actually was no real problem, just my misunderstanding of how it should work. I did a comparison between your project and the microsoft api that we are using atm, and the results were almost identical so this gives us the confidence score of 0.98 :) for moving to this project instead which is pretty darn sweet.
