### ISSUE TITLE
face detection using webcam

### ISSUE THREAD

**Issue by vijaysagi** [justadudewhohacks/face-recognition.js#31]
Hi,

can u pls let me know how to detect the face from webcam for face recognition. I tried the code but somehow am stuck

Pls suggest

**Comment by justadudewhohacks** [comment]
Hi,

Which code did you try? Using only this package you can only read jpeg and png images. For everything else such as video streams, webcam etc. you have to use it with opencv4nodejs.

There are examples how to read frames from a webcam with opencv4nodejs.

**Comment by vijaysagi** [comment]
actually i was trying with face-recognition.js framework but somehow was stuck. anyways, thanks for the update
