### ISSUE TITLE
npm install face-recognition fails

### ISSUE THREAD

**Issue by HackPoint** [justadudewhohacks/face-recognition.js#34]
Node: 9.3.0
OS: darwin x64

  CXX(target) Release/obj.target/facerec/cc/FaceRecognizerNet.o
  SOLINK_MODULE(target) Release/facerec.node
ld: warning: directory not found for option '-L/usr/X11/lib'
ld: library not found for -lX11
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/facerec.node] Error 1

**Comment by justadudewhohacks** [comment]
You need to have some kind of libx11 installed currently, for the GUI parts of dlib. For Mac OSX it's available under the xquartz project.

**Comment by m-onz** [comment]
Don't forget to log out and then log back in again once you've install xquarts for it to take affect. 

https://www.xquartz.org/

And don't forget CMAKE!

https://cmake.org/download/

**Comment by justadudewhohacks** [comment]
Closing, if after setting up xquartz it still does not work, feel free to reopen.
