### ISSUE TITLE
Unable to install on 32-bit Windows OS

### ISSUE THREAD

**Issue by pratikgchaudhari** [justadudewhohacks/face-recognition.js#40]
Hi,
I need to build my project for 32-bit systems.
Hence I have built [dlib](https://github.com/davisking/dlib) for 32-bit Windows and have set the DLIB_INCLUDE_DIR & DLIB_LIB_DIR in windows PATH variable.
But I am getting following error:

C:\face-detector>npm i face-recognition@0.4.0

dlib-build@0.0.6 install C:\face-detector\node_modules\dlib-build
 node ./install.js

found dlib
DLIB_INCLUDE_DIR: C:\prj\dlib_build_release\include
DLIB_LIB_DIR: C:\prj\dlib_build_release\lib

 face-recognition@0.4.0 install C:\face-detector\node_modules\face-recognition
 node-gyp rebuild

C:\face-detector\node_modules\face-recognition>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_
modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_mo
dules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: win-x86/node.lib local checksum 4514e8d359637abcf994f36fc110b956c73344e761773de5e9c72a0cccec59b5 not match remote
 c4edece2c0aa68e816c4e067f397eb12e9d0c81bb37b3d349dbaf47cf246b0b7
gyp ERR! stack     at deref (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:266:20)
gyp ERR! stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:384:24)
gyp ERR! stack     at emitOne (events.js:121:20)
gyp ERR! stack     at Request.emit (events.js:211:7)
gyp ERR! stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1085:12)
gyp ERR! stack     at Object.onceWrapper (events.js:313:30)
gyp ERR! stack     at emitNone (events.js:111:20)
gyp ERR! stack     at IncomingMessage.emit (events.js:208:7)
gyp ERR! stack     at endReadableNT (_stream_readable.js:1055:12)
gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node
-gyp.js" "rebuild"
gyp ERR! cwd C:\face-detector\node_modules\face-recognition
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! face-recognition@0.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1

OS: Windows 7, 32-bit
Node: v8.9.4
npm: 5.6.0

**Comment by justadudewhohacks** [comment]
Hmm, no clue sorry, node checksum seems to not match. You are better off asking the guys at node-gyp what the issue is.

**Comment by pratikgchaudhari** [comment]
I found this [Issue 693](https://github.com/nodejs/node-gyp/issues/693) in [node-gyp's](https://github.com/nodejs/node-gyp) repo. But it isn't of much help.

I even tried installing it without using my own build of [dlib](https://github.com/davisking/dlib) and let npm download and build [dlib](https://github.com/davisking/dlib) using [VS2017 build tools](https://www.visualstudio.com/downloads) but it still throws the same error.

Is there any other way?

**Comment by justadudewhohacks** [comment]
The error is thrown by node-gyp in the install script, when trying to install the node headers. The auto build of dlib is currently hardcoded to x64, so I would definitely use an own build of dlib for that.

**Comment by pratikgchaudhari** [comment]
As I have stated before, I had initially used my own build of [dlib](https://github.com/davisking/dlib) for 32-bit Windows but still encountered the aforementioned error.
Later on I tried using the auto build.

**Comment by justadudewhohacks** [comment]
Yes I know, just saying you should stick with your own build. I have no clue what could cause this problem as I never ran into this, sorry. Maybe also https://github.com/nodejs/node-gyp/issues/724 helps, or upgrading npm/ the node-gyp version that comes bundled with npm.

**Comment by pratikgchaudhari** [comment]
Nope. Still getting the same error.
I give up.
Thanks anyway.

**Comment by pratikgchaudhari** [comment]
Feel free to close this issue.

**Comment by justadudewhohacks** [comment]
Okay, well one could also set download the node headers manually and set the node path with `--nodedir` or  `--tarball` flag on npm install.
https://github.com/nodejs/node-gyp/issues/1133
