### ISSUE TITLE
Cannot find module "../build/Release/facerec"

### ISSUE THREAD

**Issue by fatangare** [justadudewhohacks/face-recognition.js#42]
When tried to use in Angular 5 project (Using IONIC framework), I am getting above error.

  fr = require('../build/Release/facerec') is causing issue,

Any idea how to fix it?

**Comment by justadudewhohacks** [comment]
Did npm install actually finish the build successfully?

**Comment by fatangare** [comment]
yes and I got face-recognition and face-recognition-models folders in node_modules

**Comment by justadudewhohacks** [comment]
And the file `facerec.node`  exists in `node_modules/face-recognition/build/Release` ?

**Comment by fatangare** [comment]
yes it exists

Following files are in node_modules/face-recognition/build/Release 
facerec.exp
facerec.lib
facerec.map
facerec.node
facerec.pdb

**Comment by justadudewhohacks** [comment]
By the way, since you are using angular. Are you using this module with electron or nw.js or are you attempting to build a single page app?

This package is a native node module, thus wont run in the browser.

**Comment by fatangare** [comment]
I am attempting to build single page app

**Comment by justadudewhohacks** [comment]
I see. Well as I said, you can not use this package in the browser, but you can run use it on a nodejs server to build a webservice.

**Comment by fatangare** [comment]
Got it...Thanks!

**Comment by gaceladri** [comment]
Hi,

I am having the same issue with yarn. I understand that it is not possible to run this package with yarn neither. Right? 

Thanks!

**Comment by justadudewhohacks** [comment]
This doesnt have to do something with yarn, sure you can use yarn. But you can not use this package in the browser, only with nodejs.

**Comment by dipanshi08** [comment]
hey,
Can I use this package with react-native?
I am having the same issue :
 **Unable to resolve module `../build/Release/facerec.node` from `/Users/../node_modules/face-recognition/lib/index.js`:The module `../build/Release/facerec.node` could not be found from `/Users/../node_modules/face-recognition/lib/index.js`.**
I have face-recognition and facerecognition-models in my project node_modules folder and,
face-recognition/build/release consists of facerec.node.

I am using react native CLI and not expo.
