### ISSUE TITLE
Load base64 image

### ISSUE THREAD

**Issue by xAKLx** [justadudewhohacks/face-recognition.js#45]
Is it possible to load a base64 string image as a ImageRGB?

I've been trying to do it using the examples of opencv-express with imdecode and fr.CvImage, but the detectFaces and locateFaces returns an empty array. It works fine when I load the same image using cv.imread.

I noticed that the results I get of imread and imdecode are different for the same image, maybe this has something to do with the IMREAD_COLOR flag applied automatically to imread in the opencv source code(?)

`"imread": {
        "step": 276,
        "elemSize": 3,
        "sizes": [
            112,
            92
        ],
        "empty": false,
        "depth": 0,
        "dims": 2,
        "channels": 3,
        "type": 16,
        "cols": 92,
        "rows": 112
    },
    "imdecode": {
        "step": 92,
        "elemSize": 1,
        "sizes": [
            112,
            92
        ],
        "empty": false,
        "depth": 0,
        "dims": 2,
        "channels": 1,
        "type": 0,
        "cols": 92,
        "rows": 112
    }`

**Comment by justadudewhohacks** [comment]
Hi,

yes it is possible to load RGB images from a base64 string with cv.imdecode. cv.imread should take a filepath as input. Are you reading the image from a file saved on your disk or did you actually plug the base64 string representation of your image into cv.imread?

Simply displaying your image with cv.imshow should give you a clue, which is the right way. Are the dimensions (92x112 pixel) correct? Seems pretty small to me, the FaceDetector won't find any faces in such small dimensions.

**Comment by xAKLx** [comment]
I used cv.imread with a local image using the path.

`detector.locateFaces(fr.CvImage(cv.imread('./10.jpg')))`

This gives me the following result:
`[
        {
            "confidence": 1.0339577198028564,
            "rect": {
                "area": 6400,
                "bottom": 99,
                "top": 20,
                "right": 91,
                "left": 12
            }
        }
    ]`

The detection of the face is working fine there, but if I instead use imdecode with the base64 representation of the same image:  

`detector.locateFaces(fr.CvImage(decodeFromBase64(base64String)))`

Being decodeFromBase64 the one used here https://github.com/justadudewhohacks/opencv-express/blob/master/src/services/imgcodecs.js, I get an empty array.

As both representation are the same image, I suspect there is a different in the final result between imread and imdecode.

pd: My goal actually doesn't have anything to do with detecting faces, as I plan to send the faces pre-detected (with only the face portion) but I am getting 'Fatal Error Filter windows must be small enough to fit into the padded image' If I just skip to the addFaces So I decided to follow the original workflow.

**Comment by justadudewhohacks** [comment]
Ah okay, I think the image you are loading is actually a gray scale image right? Thus cv.imdecode returns a 1 channel matrix and cv. imread 3 channel matrix as `IMREAD_COLOR` is default I think, as you already said. Actually `fr.CvImage` expects the image contain BGR data, so you would probably have to pass a flag to cv.imdecode to return a color image instead.

But the minimum input image size for the neural net used by the FaceRecognizer is somewhat like 105x105, so your image is definitely to small, which is why you are receiving the error probably. You could simply scale your images up to a size of 105x105 for that purpose.

**Comment by xAKLx** [comment]
Hello,

I tried to convert the image to RGB, but it didn't work either. After resizing the image using the resize method of the cvimage, the face was detected properly. Thanks for your help. 

`detector.locateFaces(fr.CvImage(decodeFromBase64(base64String).resize(128, 128)))`

**Comment by justadudewhohacks** [comment]
Okay that's strange. I would expect `fr.CvImage` to return complete garbage if you give it a 1 channel matrix.
