### ISSUE TITLE
Use base64 format images for identification?

### ISSUE THREAD

**Issue by lixin2628** [justadudewhohacks/face-recognition.js#49]
Use base64 format images for identification?

**Comment by justadudewhohacks** [comment]
Hi

> Using only this package you can only read jpeg and png images. For everything else such as video streams, webcam etc. you have to use it with opencv4nodejs.

There are examples on how to use this package with opencv4nodejs. With opencv you can decode from and encode to base64 strings to images. See also this issue #45
