### ISSUE TITLE
How can i save recognized faces?

### ISSUE THREAD

**Issue by zurek11** [justadudewhohacks/face-recognition.js#50]
Hi. Thank you for you amazing library. I have some questions. 
1. How can i save images after const faceImages = detector.detectFaces(image); ??
2. Is there some way to view the whole image with recognized faces in rectangles? Like in your examples and of course save them?

**Comment by justadudewhohacks** [comment]
Hi,

1. You can do this with` fr.saveImage`. Consider the following function signature: `export function saveImage(path: string, image: ImageRGB | ImageGray, isJpeg?: boolean): void;`

2. The rectangles in the examples are drawn as an overlay on a window. With this package you can't draw rectangles directly into the image. You can however use this package with opencv4nodejs (see examples), which allows you to draw rectangles on an image and save it.
