### ISSUE TITLE
Problem modifying .cc files

### ISSUE THREAD

**Issue by xAKLx** [justadudewhohacks/face-recognition.js#52]
When I modify one of the .cc files (utils.cc and utils.h) the changes doesn't affect the build. I know that the build knows about my changes because if I do something wrong, the build throws an error and stop. But after the build, I went to the face-recognition folder inside the node_modules and the .cc file has the original version instead of my edited version. Why does this happen?

Pd: the purpose of my modifications is to use dlib::assign_image to convert a CvImage to an ImageRGB because the face68LandmarkPredictor only works with ImageRGB.

**Comment by justadudewhohacks** [comment]
Hi,

My guess is, if you want to modify the files, you would have to clone this repo. Modifying the files inside node_modules will probably just pull the original files from npm again once you npm install.

**Comment by xAKLx** [comment]
Hello,

Yes, I am using a local copy of the repo, and I am requiring it in the package.json like this:
`"face-recognition": "file:./face-recognition"`. But for some reason, what gets to the node_modules is the original version, even though it throws errors during the build(npm install) if I do something wrong.

**Comment by justadudewhohacks** [comment]
Okay, why are you adding a dependency to face-recognition in the package.json of face-recognition itself? That doesn't quite make sense to me. You could just obey that line.

**Comment by xAKLx** [comment]
No, I am adding it to the package.json of my personal project, to use the library there.

**Comment by justadudewhohacks** [comment]
Ah I see. Well that's odd. You could try to move then face-recognition package outside of your working directory. I usually do it like "face-recognition": "../face-recognition" when developing locally.

**Comment by xAKLx** [comment]
It didn't work even using a git link to my own fork in the dependencies or moving the directory outside. But in the end I copied the files to the node_modules and performed a `npm run install` inside the directory. Now is working properly.
