### ISSUE TITLE
How can i draw rectangle with data of the recognized faces?

### ISSUE THREAD

**Issue by AndresED** [justadudewhohacks/face-recognition.js#53]
How can i draw rectangle with data of the recognized faces?

**Comment by justadudewhohacks** [comment]
Hi,

If you want to display rectangles around the faces look at this example: [faceLocations.js](https://github.com/justadudewhohacks/face-recognition.js/blob/master/examples/faceLocations.js).

If you want to draw them directly on the image and then save this image, have a look at #50.
