### ISSUE TITLE
How to improve performance? 

### ISSUE THREAD

**Issue by klimentLambevski** [justadudewhohacks/face-recognition.js#58]
Hi, very good work on the project.

I have a question about performance. I am running live face recognition on my laptop webcam and i measured the time that need to work one frame (~0.5s). I am using 3 faces for recognition and there is one face on the webcam(mine).

Here is the code

```
const recognizeFaces2 = (detections) =>
    Promise.all(detections.map(recognizeFace));

const recognizeFace = (det) => {
    const {rect, face} = det;
    const cvFace = fr.CvImage(face);
    console.time('detection time');
    return recognizer.predictBest(cvFace, UNKNOWN_TRESHHOLD)
        .then((prediction) => {
            console.timeEnd('detection time');
            const text = `${prediction.className} (${prediction.distance})`;
            return {
                rect,
                text
            }
        })
};

const requestFrame = (videoCap) => {
    let frame = videoCap.read();
    return Promise.resolve(frame);
};

const detectCvFaces = (frame) => {
    const options = {
        minSize: new cv.Size(80, 80),
        scaleFactor: 1.1,
        minNeighbors: 3
    };
    let faces = classifier.detectMultiScaleGpu(frame.bgrToGray(), options);
    return faces.map(rect => ({
        rect,
        face: frame.getRegion(rect).resize(150, 150)
    }));
};

const drawRecognizedFaces = (videoCap) =>
    (faces) => requestFrame(videoCap)
        .then((frame) => {
            faces.forEach(({rect, text}) => {
                const blue = new cv.Vec(255, 0, 0);
                drawRectWithText(frame, rect, text, blue);
            });
            if(faces.length) {
                cv.imshow(`face detection`, frame);
                return faces
            } else {
                return new Promise((resolve, reject) => {
                    setTimeout(() => {
                        cv.imshow(`face detection`, frame);
                        resolve(faces);
                    }, 30)
                })
            }

        });


const recognizeFaceAndDraw = (videoCap) =>
    requestFrame(videoCap)
        .then(detectCvFaces)
        .then(recognizeFaces2)
        .then(log('recognized faces'))
        .then(drawRecognizedFaces(videoCap))
        .then(() => recognizeFaceAndDraw(videoCap));

const runFaceRecognition2 = (src) => {
    const cap = new cv.VideoCapture(src);

    recognizeFaceAndDraw(cap);
};
const recognizeFaces2 = (detections) =>
    Promise.all(detections.map(recognizeFace));

const recognizeFace = (det) => {
    const {rect, face} = det;
    const cvFace = fr.CvImage(face);
    console.time('detection time');
    return recognizer.predictBest(cvFace, UNKNOWN_TRESHHOLD)
        .then((prediction) => {
            console.timeEnd('detection time');
            const text = `${prediction.className} (${prediction.distance})`;
            return {
                rect,
                text
            }
        })
};

const requestFrame = (videoCap) => {
    let frame = videoCap.read();
    return Promise.resolve(frame);
};

const detectCvFaces = (frame) => {
    const options = {
        minSize: new cv.Size(80, 80),
        scaleFactor: 1.1,
        minNeighbors: 3
    };
    let faces = classifier.detectMultiScaleGpu(frame.bgrToGray(), options);
    return faces.map(rect => ({
        rect,
        face: frame.getRegion(rect).resize(150, 150)
    }));
};

const drawRecognizedFaces = (videoCap) =>
    (faces) => requestFrame(videoCap)
        .then((frame) => {
            faces.forEach(({rect, text}) => {
                const blue = new cv.Vec(255, 0, 0);
                drawRectWithText(frame, rect, text, blue);
            });
            if(faces.length) {
                cv.imshow(`face detection`, frame);
                return faces
            } else {
                return new Promise((resolve, reject) => {
                    setTimeout(() => {
                        cv.imshow(`face detection`, frame);
                        resolve(faces);
                    }, 30)
                })
            }

        });


const recognizeFaceAndDraw = (videoCap) =>
    requestFrame(videoCap)
        .then(detectCvFaces)
        .then(recognizeFaces2)
        .then(log('recognized faces'))
        .then(drawRecognizedFaces(videoCap))
        .then(() => recognizeFaceAndDraw(videoCap));

const runFaceRecognition2 = (src) => {
    const cap = new cv.VideoCapture(src);

    recognizeFaceAndDraw(cap);
};
```

I have tried face-recognition.py and it recognizes faces in real time. I know that both libraries are build on top of dlib

I am on windows machine.

Thanks in advance

**Comment by justadudewhohacks** [comment]
Could you tell me the individual timings for `videoCap.read()`, `detectMultiScaleGpu` and `predictBest`, to figure out which one is the bottleneck.

I suspect it's the prediction as you probably don't have openblas. On linux one can simply apt-get install openblas, whereas on windows it's not that easy. On my windows machine I had to compile [OpenBLAS](https://github.com/xianyi/OpenBLAS/wiki/Installation-Guide) and enable blas when building dlib and link it to this package. I will soon add instructions how to set up this package with openblas on windows.

Did you run face-recognition.py on your windows machine and does it run right out of the box? I thought you would have to pass a flag here to enable openblas as well.

**Comment by klimentLambevski** [comment]
I am only measuring recognizer.predictBest performance. I didn't success building face-recognition.py on windows, i only tried it on linux. I had problem Boost library on windows. 

I will try building OpenBLAS and linking dlib, will report my progress.

Thanks

**Comment by justadudewhohacks** [comment]
Ah i see. I noticed dlib to have better performance on linux though.

**Comment by klimentLambevski** [comment]
I managed to build OpenBLAS on windows. How do i specify the path to OpenBLAS build so dlib can read it?

**Comment by justadudewhohacks** [comment]
After building openblas you should end up with a .lib and a .dll. Then you have to go the [manual-build](https://github.com/justadudewhohacks/face-recognition.js#manual-build) way and you have to add DLIB_USE_BLAS=ON and BLAS_Accelerate_LIBRARY=<path to openblas.lib> to the cmake configuration when building dlib.

In order to build the npm package you then have to link openblas here as well. You can simply add a 
`console.log('<path to openblas.lib>')` at the end of the script /lib/libs.js of the face-recognition package. Finally the path to openblas.dll has to be in your system path.

**Comment by justadudewhohacks** [comment]
Just published support for openblas. You might want to check out the [install instuctions](https://github.com/justadudewhohacks/face-recognition.js#boosting-performance).

**Comment by klimentLambevski** [comment]
This is far as i got, i got this error with IntelMKL yesterday
![image](https://user-images.githubusercontent.com/2531818/37059427-bc5de7b0-218d-11e8-9a95-a71666e921d5.png)
Maybe i am missing something

**Comment by justadudewhohacks** [comment]
Did you link the library as described above?

**Comment by klimentLambevski** [comment]
Yes i linked the library in environment variables
OPENBLAS_LIB_DIR C:\Users\klime\openblas\OpenBLAS\build\lib
I noticed that you are saying libopenblas.lib has to be in the path of OPENBLAS_LIB_DIR but this is the contents of the build/lib folder
![image](https://user-images.githubusercontent.com/2531818/37060064-71d819a2-218f-11e8-848c-7ded8477ab70.png)

**Comment by justadudewhohacks** [comment]
Ah well, you got the IntelMKL library, building openblas from the repo I linked spits out **libopenblas.lib**. Maybe try to rename the .lib file to **libopenblas.lib**? :D

**Comment by klimentLambevski** [comment]
Yes i am trying that now :D, will see how it goes

**Comment by klimentLambevski** [comment]
Fortunately i managed to build it, but unfortunately the processing time is the same. 
Thanks for your help man, I will try it on maxOS and linux and see how it goes
