### ISSUE TITLE
unable to install face-recognition.js

### ISSUE THREAD

**Issue by vijaysagi** [justadudewhohacks/face-recognition.js#6]
Hi all,

I tried to install  by the command **npm install face-recognition** 

Error:

npm ERR! weird error 1
npm ERR! Error: ENOENT, lstat '/home/vijay/node_modules/face-recognition/node_modules/nan/nan.h'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-97-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "face-recognition"
npm ERR! cwd /home/vijay/vijay/crowdpersona_05-01-18/JavaScript_FaceReconition
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/vijay/node_modules/face-recognition/node_modules/nan/nan.h
npm ERR! fstream_path /home/vijay/node_modules/face-recognition/node_modules/nan/nan.h
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/vijay/node_modules/face-recognition/node_modules/face-recognition-models/models/dlib_face_recognition_resnet_model_v1.dat'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-97-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "face-recognition"
npm ERR! cwd /home/vijay/vijay/crowdpersona_05-01-18/JavaScript_FaceReconition
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/vijay/node_modules/face-recognition/node_modules/face-recognition-models/models/dlib_face_recognition_resnet_model_v1.dat
npm ERR! fstream_path /home/vijay/node_modules/face-recognition/node_modules/face-recognition-models/models/dlib_face_recognition_resnet_model_v1.dat
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)

FATAL ERROR: JS Allocation failed - process out of memory
Aborted (core dumped)

FYI:
 OS: Ubuntu 14.04
Python version : 2.7
npm version: 2.15.11
nodejs version: v0.12.18

Pls suggest the way forward

Thanks
vijay

**Comment by justadudewhohacks** [comment]
Hey,

I would suggest upgrading your node version. Node 6+ should work.

**Comment by iamblue** [comment]
Node 8 work for me.

**Comment by justadudewhohacks** [comment]
Closing, if upgrading the node version to atleast node 6 doesn't solve the issue, feel free to reopen.

**Comment by vijaysagi** [comment]
thnk u its working
