### ISSUE TITLE
Big Size Images makes computer slow

### ISSUE THREAD

**Issue by anouarkacem** [justadudewhohacks/face-recognition.js#61]
I am not sure if this is a library issue or machine issue (tried it on 2 powerful computers with different OS windows + ubuntu but same result).
Anyways, the first try with a simple images 600x400, size around 100kb-250kb and the detecting faces result was just after 7sec which is a lot for me since I am going to detect thousands of faces.
- Using sizes like 500-999kb takes 1-2min to detect the faces
- Over 1MB, huge problems computer get slower and for an image 2-3MB the computer stopped working.

Well, I know I can resize the image before detecting the face, I just wanted to know this issue where is coming from, is it normal or just me ... note this only detecting `fr.FaceDetector()` I didn't even start to recognize faces

**Comment by justadudewhohacks** [comment]
Hi,

You might want to have a look at: [boosting-performance](https://github.com/justadudewhohacks/face-recognition.js#boosting-performance).

**Comment by anouarkacem** [comment]
@justadudewhohacks  

> Simply install openblas (sudo apt-get install libopenblas-dev) before building dlib / installing the package.

How can I do it since I have already built the dlib without installing libopenlabs-dev, shall I remove it and resintall again ?

**Comment by justadudewhohacks** [comment]
Did you build dlib manually or via the auto build when npm installing this package?

If you are using the auto build, I would do `npm uninstall face-recognition && npm install face-recognition`.

If you are using a manual build you also have to rebuild dlib before reinstalling the package.

**Comment by justadudewhohacks** [comment]
Could you show me the log output of cmake? With openblas installed you should find openblas being detected as follows:

![61](https://user-images.githubusercontent.com/31125521/37333073-ae44f1a8-26a8-11e8-80b9-438b451b4f02.png)

**Comment by Zwimber** [comment]
To be honest I think most of the taks are rather CPU intensive regardless of using OpenBLAS or not. On my Macbook Pro I get the following results with this script:

```javascript
const detector = fr.FaceDetector()
const faceRectangles = detector.locateFaces(image)
```

- 256 x 256px about 200ms
- 512 x 512px about 800ms
- 1024 x 1024px about 2000ms

Which all are a way to slow for any realtime application. If you still want to go ahead there's several ways to improve the speed which I have found:

1. Accept the fact that for the realtime part of your application you will use downscaled versions of the original image. You can store the original image for later use. 
2.  Create a smaller copy of the image (e.g. 128px) then use `locateFaces`. Then use `locateFaces` on the larger image only on the area's where an face has been found. 
3. Use a haarclassifier (either from opencv or from this library), then use `locateFaces` on the larger image only on this area. The haarclassifier is much faster (about 200ms on 1024x1024) on my device.

```javascript
// Please note that this detector will only detect frontal faces!
let detectorOpenCV = new cv.CascadeClassifier(cv.HAAR_FRONTALFACE_DEFAULT);

let imageGray = imageCvMat.bgrToGray()
let detect = detectorOpenCV.detectMultiScale(imageGray)
// Also please note that there's an async variant for these functions!
```

**Comment by thexiroy** [comment]
@Zwimber Regarding option 3 where could I find the haarclassifier from this library? I intend to use the face detection for a webcam stream which requires lower latency.

**Comment by thexiroy** [comment]
@Zwimber Regarding option 3, where can I find the haarclassifier from this library? I need low latency because I want to try it out with a webcam stream.

**Comment by justadudewhohacks** [comment]
The `CascadeClassifier` comes from opencv4nodejs. You can find some examples here, how to use face-recognition.js with opencv4nodejs.
