### ISSUE TITLE
CvImage from cvMat with only one channel

### ISSUE THREAD

**Issue by legraphista** [justadudewhohacks/face-recognition.js#62]
Hi! 
I'm working with a one channel buffer that contains only the luminance part of the image and would like to use `FaceDetector.locateFaces`.

The issue that I encountered is that `CvImage` expects only a `cv.Mat` with 3 channels:
```js
const mat = new cv.Mat(buffer, height, width, cv.CV_8UC1);
const image = fr.CvImage(mat);
const detector = new fr.FaceDetector()
detector.locateFaces(image); // -> outputs no faces (there are 2)

const win = new fr.ImageWindow();
win.setImage(image); // -> will display a squashed version of the image, repeated 3 times on the horizontal axis.
```

As a workaround, one can duplicate the channel 3 times in order to fill the gap: 
```js
const fakeRGB = Buffer.alloc(buffer.length * 3);
for (let i = 0, j = 0; i < buffer.length; i++, j += 3) {
      fakeRGB[j + 0] = buffer[i];
      fakeRGB[j + 1] = buffer[i];
      fakeRGB[j + 2] = buffer[i];
}
const cvMat = new cv.Mat(fakeRGB, height, width, cv.CV_8UC3);
const cvImage = new fr.CvImage(cvMat);

detector.locateFaces(cvImage); // -> expected output
const win = new fr.ImageWindow();
win.setImage(image);  // -> normal image
```

Is there any other way around this that is less taxing because of the conversions?

**Comment by justadudewhohacks** [comment]
Hi,

You should be able to simply convert your single channeled gray Mat to a three channel gray Mat with `mat.cvtColor(cv.CV_GRAY2BGR)`.

**Comment by legraphista** [comment]
Hi @justadudewhohacks. Thank you for the quick answer!

Substituting from the second example:
```js
const cvMat = new cv.Mat(fakeRGB, height, width, cv.CV_8UC3);
const cvImage = new fr.CvImage(cvMat);
``` 
with
 ```js
const cvMat = new cv.Mat(buffer, height, width, cv.CV_8UC1);
const cvImage = new fr.CvImage(cvMat.cvtColor(cv.COLOR_GRAY2RGB));
```
did the trick, and it seams to be less expensive as well.
