### ISSUE TITLE
throw new Error('predict - expected FaceRecognizer to be trained with at least 2 different classes')

### ISSUE THREAD

**Issue by harryyuanfeng** [justadudewhohacks/face-recognition.js#63]
I am getting this error:

`throw new Error('predict - expected FaceRecognizer to be trained with at least 2 different classes')`

What is the possible cause of this one?

**Comment by iamsashank09** [comment]
TRY mORE TRAING

**Comment by justadudewhohacks** [comment]
Well its what the error says, you have to train the model with two different classes (persons) first
