### ISSUE TITLE
Error: FaceRecognizerNet::ComputeFaceDescriptor - Error: expected argument 0 to be of type ImageRGB

### ISSUE THREAD

**Issue by harryyuanfeng** [justadudewhohacks/face-recognition.js#64]
What is the possible cause of this one?

`
Error: FaceRecognizerNet::ComputeFaceDescriptor - Error: expected argument 0 to be of type ImageRGB`

**Comment by justadudewhohacks** [comment]
Also what the error says, the thibg you are passing to the face recognizer is either not an image or undefined
