### ISSUE TITLE
[feature] Support for binary buffers in loadImage

### ISSUE THREAD

**Issue by SkeLLLa** [justadudewhohacks/face-recognition.js#67]
Hi. I don't know if it's possible to add support for buffers in `loadImage` or some new function. I've looked through the code and it seems that files reading is handled inside dlib and I didn't find any easy way to do a quick PR.

This feature could be utilized in cases when images are stored not on disk (so previously you will get them from somewhere) or images could be preprocessed. So, in this case, they will be loaded into memory as Buffer and storing them to disk and then performing cleanup will add unnecessary overhead.

**Comment by Zwimber** [comment]
Although I do agree that it would be a nice function to immediatly pass buffers to the `loadImage` function, there is a simple workaround to work with buffers using openCV imdecode function. 

```javascript
let cv = require('opencv4nodejs')
let fr = require('face-recognition').withCv(cv)
```

You can easily use an buffer without writing it to your disk:

```javascript
let buffer = new Buffer()
let imageCvMat = cv.imdecode(buffer) // There is also imdecodeAsync!
```
And then transform it for your needs:
```javascript
let imageCv = fr.CvImage(imageCvMat)
let imageRgb = fr.cvImageToImageRGB(data.imageCv)
```

**Comment by SkeLLLa** [comment]
@Zwimber , thanks. I've started looking through that opencv4nodejs methods to do that. I'll try to do that in such way, but I'm not sure if it will work because I use face detection which uses `dlib`, if I understood the code correctly.

**Comment by justadudewhohacks** [comment]
It will work as @Zwimber suggested. You can use this package with opencv4nodejs to do image processing and do face recognition with face- recognition.js . There are examples that should guide you. Opencv4nodejs allows you all kinds of matrix creating, from raw data, from encoded images, base64 images, video, webcam etc.

Standalone, this package only allows to read jpg and png images There is no other way then using opencv4nodejs. It's not straight forward to initialize image matrices from raw data in dlib other then implementing a own wrapper class, which I did for opencv bgr images.

**Comment by SkeLLLa** [comment]
@justadudewhohacks, thanks. 
I just used pure opencv4nodejs and `CascadeClassifier`. And it worked with buffers. And face-recognition.js face detector seems working much slower than opencv's. So anyway the last solution satisfied all my needs.

As I said, I've looked through dlib sources and didn't find a way to use buffers, just thought maybe I've missed something.

**Comment by justadudewhohacks** [comment]
Ok. Yes face detection with opencv is way faster but not as stable. If that's applicable for you and don't need face recognition, then I would stick with opencv4nodejs.
