### ISSUE TITLE
Please add API to save image with Face Landmarks

### ISSUE THREAD

**Issue by Andrey2509** [justadudewhohacks/face-recognition.js#69]
Please add API to save image with Face Landmarks

**Comment by justadudewhohacks** [comment]
Unfortunately not possible. However, you can draw the results with opencv4nodejs. Same as #23

**Comment by Zwimber** [comment]
Why would you want to save the image with the landmarks on it? I would recommend to save them keep them clean and separate, get the parts use the following: 

```javascript
let shapes68 = predictor68.predict(images, rect))
let shapes68parts = shapes68.getParts()
```

It is easy to later on combine the image and for example a canvas.

**Comment by Andrey2509** [comment]
I make frontend for face recognition of live ip cameras wich generates jpeg if motion detected on Linux Debian. I want to analyze unknown faces and have statistic, so I don't need real time effects on Windows OS.To have images with faces landmarks for test, study and check will be perfect.. If you know simple way to export images with faces landmarks please let me know (source code).  26.03.2018, 15:20, "Zwimber" <notifications@github.com>:Why would you want to save the image with the landmarks on it? I would recommend to save them keep them clean and separate, get the parts use the following:let shapes68 = predictor68.predict(images, rect))
let shapes68parts = shapes68.getParts()It is easy to later on combine the image and for example a canvas.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
