### ISSUE TITLE
How can this scale, e.g. with 10000 faces?

### ISSUE THREAD

**Issue by anhcao142** [justadudewhohacks/face-recognition.js#7]
Just like you, I used dlib to detect and recognize faces. It's fine with just couple of faces, like 10 or 20, but when we hit more than 1000 the program became extremely slow.

Do you test your lib with more than 1000 faces? Can it scale?

**Comment by m-onz** [comment]
@boylove142  Try segmenting the image and processing it in batches with micro-services and pipelines... you don't need to run 1000 faces at once. Its possible to architect your system around these limitations.

**Comment by anhcao142** [comment]
I no longer follow this project so I'll close this now
