### ISSUE TITLE
CvImageWrap to ImageRGB

### ISSUE THREAD

**Issue by nicholasc** [justadudewhohacks/face-recognition.js#72]
I have a loop in which I read a frame from a webcam using opencv4nodejs's `VideoCapture` and then I get the faces using a simple `CascadeClassifier` object. I want to use the rectangles from the classifier with dlib's landmark detector so I convert the frame to a CvImage but when I put the image in the predictor I get:

`Error: ShapePredictor::Predict - Error: expected argument 0 to be of type ImageRGB`

I was converting the frame to greyscale before and even when removing that it still fails.
The converted frame is a `CvImageWrap` object when I log it. 

Is there a way to convert this to an ImageRGB? Thanks

Here is the full code of my example:
```js
const cv = require("opencv4nodejs");
const fr = require("face-recognition").withCv(cv);

const drawRect = (image, rect, color, opts = { thickness: 2 }) =>
  image.drawRectangle(rect, color, opts.thickness, cv.LINE_8);

const predictor = fr.FaceLandmark68Predictor();
const classifier = new cv.CascadeClassifier(
  "./lbpcascade_frontalface_improved.xml"
);

const webcam = new cv.VideoCapture(0);
webcam.set(cv.CAP_PROP_FRAME_WIDTH, 640);
webcam.set(cv.CAP_PROP_FRAME_HEIGHT, 400);

for (;;) {
  const frame = webcam.read();
  if (frame.empty) continue;

  const { objects } = classifier.detectMultiScale(frame);

  const img = fr.CvImage(frame);

  objects.forEach((rect, i) => {
    const shapes = predictor.predict(img); // <--- this is where it crashes
    drawRect(frame, rect, new cv.Vec(0, 255, 0), { thickness: 1 });
  });

  cv.imshow("VideoCapture", frame);
  cv.waitKey(10);
}
```

**Comment by Zwimber** [comment]
I think this is what you are looking for. To get a full list of the functions available you could always try: `console.log(fr)` the names are pretty descriptive.

```javascript
let imageCv = fr.CvImage(imageMat)
let imageRgb = fr.cvImageToImageRGB(imageCv)
```

**Comment by nicholasc** [comment]
@Zwimber exactly what I was looking for. I appreciate the tip given that there is documentation for the lib.

Closing.
