### ISSUE TITLE
Which windows 10 sdk?

### ISSUE THREAD

**Issue by kostadinnm** [justadudewhohacks/face-recognition.js#73]
Hello
I'm trying to test out face detection with dlib and javascript. I've cloned this repo and tried running the install script. I installed all other prerequisites except for the "windows 10 sdk". Which one should I use:
![2018-04-02 17_31_17-face-detection](https://user-images.githubusercontent.com/18436405/38200375-b6b01882-369c-11e8-903b-a55a1eaca2a3.jpg)
I tried looking at [https://github.com/felixrieseberg/windows-build-tools](https://github.com/felixrieseberg/windows-build-tools), but no clues there as well.

Although I like the package-like management for libraries I tend to stay away from it when it comes to frameworks/sdks/build-engines on windows. Moreover, it's better to have local-only node packages anyway - I've seen it recommended here and there. I guess I'll just go with the highest version w/o extra title(Windows 10 SDK (10.0.14393.0)), but anyone's welcome to bring some more clarity which's the preferable approach?!

**Comment by justadudewhohacks** [comment]
Hi,

Regarding to this [node-gyp issue](https://github.com/nodejs/node-gyp/issues/1144), you should only select 10.0.14393.0 and unselect all of the other sdk tools. I think that's what I did on my machine as well.

**Comment by kostadinnm** [comment]
I decided to go for the latest - 10.0.16299.0, which builds w/o errors. But I'm planning to use it within an electron app, so I may need to downgrade(as the author of the node-gyp issue). Thanks

Cheers,
Kostadin
