### ISSUE TITLE
All faces not loaded from model.json.

### ISSUE THREAD

**Issue by Andrey2509** [justadudewhohacks/face-recognition.js#77]
I have 3 faces for className "andrey" and and 2 faces for className "yurii" , wich I previously saved to model.json using:
`const modelState = recognizer.serialize();
 fs.writeFileSync('model.json', JSON.stringify(modelState));
`

I did non find any mistake in file model.json.
But the commands:

```
const modelState = require('model.json');
recognizer.load(modelState);
console.log('face_db after add new faces='+JSON.stringify(recognizer.getDescriptorState()));
```
show me only 1 face:
`face_db after add new faces=[{"className":"andrey","numFaces":1}]`

**Comment by Zwimber** [comment]
Hi Andrey, it seems you are just reading in the wrong `model.json`. Downloading & reading in the provided model.json.zip. I get:

```[{"className":"andrey","numFaces":3},{"className":"yurii","numFaces":2}]```

**Comment by Andrey2509** [comment]
Now I try to use:
```
var decache = require('decache');
decache(trainedModelFile);
recognizer.load(require(trainedModelFile));
```
to use actual version of  trainedModelFile file. Nodejs seems to cache it.

**Comment by justadudewhohacks** [comment]
Yeah probably the require cache

**Comment by Andrey2509** [comment]
`decache(trainedModelFile);` does not clear cache .
Is any other method to load actual version trainedModelFile in `recognizer.load(require(trainedModelFile));` ?

**Comment by Andrey2509** [comment]
Thanks!
