### ISSUE TITLE
error with make (with a RPI3)

### ISSUE THREAD

**Issue by StefT09** [justadudewhohacks/face-recognition.js#81]
Hello,
on a raspeberry pi 3, I try "npm install face-recognition" but i have this :
Any idea to resolve this pb ?
Thank

pi@raspberrypi:~ $ npm install face-recognition

> face-recognition@0.8.1 install /home/pi/node_modules/face-recognition
> node-gyp rebuild

make : on entre dans le répertoire « /home/pi/node_modules/face-recognition/build »
  CXX(target) Release/obj.target/facerec/cc/index.o
  CXX(target) Release/obj.target/facerec/cc/ImageRGB.o
  CXX(target) Release/obj.target/facerec/cc/ImageGray.o
  CXX(target) Release/obj.target/facerec/cc/CvImage.o
  CXX(target) Release/obj.target/facerec/cc/Rect.o
  CXX(target) Release/obj.target/facerec/cc/MmodRect.o
  CXX(target) Release/obj.target/facerec/cc/FullObjectDetection.o
  CXX(target) Release/obj.target/facerec/cc/Point.o
  CXX(target) Release/obj.target/facerec/cc/Array.o
 CXX(target) Release/obj.target/facerec/cc/ChipDetails.o
  CXX(target) Release/obj.target/facerec/cc/utils.o
  CXX(target) Release/obj.target/facerec/cc/ImageWindow.o
  CXX(target) Release/obj.target/facerec/cc/ShapePredictor.o
In file included from /home/pi/node_modules/native-node-utils/src/Converters.h:3:0,
                 from ../cc/ShapePredictor.h:1,
                 from ../cc/ShapePredictor.cc:1:
/home/pi/node_modules/native-node-utils/src/Workers.h: In instantiation of ‘void GenericAsyncWorker<Context>::HandleOKCallback() [with Context = ShapePredictor::PredictWorker]’:
../cc/ShapePredictor.cc:71:1:   required from here
/home/pi/node_modules/native-node-utils/src/Workers.h:27:17: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   callback->Call(2, argv);
   ~~~~~~~~~~~~~~^~~~~~~~~
In file included from /home/pi/node_modules/native-node-utils/src/AbstractConverter.h:1:0,
                 from /home/pi/node_modules/native-node-utils/src/TypeConverters.h:1,
                 from /home/pi/node_modules/native-node-utils/src/Converters.h:1,
                 from ../cc/ShapePredictor.h:1,
                 from ../cc/ShapePredictor.cc:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
In file included from /home/pi/node_modules/native-node-utils/src/Converters.h:3:0,
                 from ../cc/ShapePredictor.h:1,
                 from ../cc/ShapePredictor.cc:1:
/home/pi/node_modules/native-node-utils/src/Workers.h: In instantiation of ‘void GenericAsyncWorker<Context>::HandleErrorCallback() [with Context = ShapePredictor::PredictWorker]’:
../cc/ShapePredictor.cc:71:1:   required from here
/home/pi/node_modules/native-node-utils/src/Workers.h:33:17: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   callback->Call(2, argv);
   ~~~~~~~~~~~~~~^~~~~~~~~
In file included from /home/pi/node_modules/native-node-utils/src/AbstractConverter.h:1:0,
                 from /home/pi/node_modules/native-node-utils/src/TypeConverters.h:1,
                 from /home/pi/node_modules/native-node-utils/src/Converters.h:1,
                 from ../cc/ShapePredictor.h:1,
                 from ../cc/ShapePredictor.cc:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~

**Comment by justadudewhohacks** [comment]
Ahh I see. Probably same issue as [this](https://github.com/justadudewhohacks/npm-opencv-build/issues/6).

**Comment by StefT09** [comment]
It will work ... i have just this warning ( sorry it's the first time i use node !)

  SOLINK_MODULE(target) Release/obj.target/facerec.node
  COPY Release/facerec.node
make : on quitte le répertoire « /home/pi/node_modules/face-recognition/build »
npm WARN pi@1.0.0 No description
npm WARN pi@1.0.0 No repository field.

**Comment by abhisheksoni27** [comment]
@justadudewhohacks Can't we provide a pre-built version of dlib.so for the Raspberry Pi? I am assuming the Pi is running out of RAM, and is a known phenomenon when compiling dlib on the board itself. There is a workaround to make it compile by adding more SWAP on the SD card but that's too much of a hassle and users shouldn't have to go through that. 

I mean we can add the swap and build it ourselves and then make it available for anyone to use it, clarifying which apt libraries they are gonna have to install before they can download the compiled dlib library.

Or maybe we can cross-compile it and make it available? What do you think?

**Comment by justadudewhohacks** [comment]
Well the idea makes sense to me. If you(or someone else) would like to upload and maintain the pre-built binaries I am willing to add that option to the install script. Personally I will not maintain that binary however.

**Comment by abhisheksoni27** [comment]
Great! I have a RPi2. I'll let you know when I have the binary available. THanks!

**Comment by StefT09** [comment]
Hello, i have installed opencv4nodejs on the Rpi3 ... it's wonderfull ! extraordinaire ! Works perfectly. Thank you for your work. I can now look at Nodejs, Opencv, I have for a life and several reincarnations !
