### ISSUE TITLE
Unknown face.

### ISSUE THREAD

**Issue by MisaZ10** [justadudewhohacks/face-recognition.js#85]
Hello, (sorry for my English).
I have a problem, I add Robert Downey jr faces then, I use FaceRecognizer with Obama but FaceRecognizer detect to Robert.

The result is "robert 0.4"
This is my proyect https://github.com/MisaZ10/prueba_face_recognition

FaceRecognizer work with unknown faces ?
My code is wrong ??

Thank you

**Comment by justadudewhohacks** [comment]
You should first of all perform face detection, to retrieve the face locations in your images, then extract the face images and feed them into the FaceRecognizer as in the example.

**Comment by MisaZ10** [comment]
Okay I'll try that and notify you.

**Comment by MisaZ10** [comment]
I change the algoritmy https://github.com/MisaZ10/prueba_face_recognition/blob/master/addFaces.js
but I have the same result. "obama-face.png" => "robert 0.79"
Now I use detectFaces before use recognizer.addFaces.

**Comment by MisaZ10** [comment]
Thank you very much, now it responds correctly! 😄
