### ISSUE TITLE
I can't figure out why it was not installing properly

### ISSUE THREAD

**Issue by nawin97** [justadudewhohacks/face-recognition.js#86]
executing: git --version
executing: cmake --version
find vs2017 via powershell: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe [ '-ExecutionPolicy',
  'Unrestricted',
  '-Command',
  '&{Add-Type -Path \'G:\\node\\face_detection\\node_modules\\dlib-build\\lib\\Find-VS2017.cs\'; [VisualStudioConfiguration.Main]::Query()}' ]
executing: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe [ '-ExecutionPolicy',
  'Unrestricted',
  '-Command',
  '&{Add-Type -Path \'G:\\node\\face_detection\\node_modules\\dlib-build\\lib\\Find-VS2017.cs\'; [VisualStudioConfiguration.Main]::Query()}' ]
failed to find vs2017 via powershell
Exception calling "Query" with "0" argument(s): "Retrieving the COM class factory for component with CLSID
{177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 80040154 Class not registered (Exception
from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))."
At line:1 char:87
+ ... build\lib\Find-VS2017.cs'; [VisualStudioConfiguration.Main]::Query()}
+                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : COMException

**Comment by S66D** [comment]
Same issue, did you find any fix?

**Comment by nawin97** [comment]
no , waiting for contributor for help!!

**Comment by nawin97** [comment]
thanks, bro for replying, are you talking about visual studio ide or visual studio code ??

**Comment by justadudewhohacks** [comment]
I am talking about visual studio (not visual studio code). Actually you only need msbuild and a c++11 compatible compiler, which is MSVC15 shipped with VS2017. Link for VS2017 build tools is in the readme.

**Comment by nawin97** [comment]
okk brother thanks again , i installed in linux and it works perfectly
