### ISSUE TITLE
What is the range of Confidence parameter in face detection?

### ISSUE THREAD

**Issue by komalpharate** [justadudewhohacks/face-recognition.js#89]

**Comment by justadudewhohacks** [comment]
Well having a distance (euclidean distance of two face vectors) of 0 means, it's an exact match. The higher the distance, the less similar. For 150x150 face images 0.6 is a good threshold to judge, whether two faces are from the same person. For smaller face images, you will probably have to adjust the threshold to be a higher value.

**Comment by komalpharate** [comment]
Thank you for your reply.
