### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error

### ISSUE THREAD

**Issue by bonkzero404** [justadudewhohacks/face-recognition.js#92]
I get an error message when face training, there is one photo that caused it happen.

**Comment by justadudewhohacks** [comment]
Can you share the image that caused the crash? My first guess is dimensions too small.

**Comment by bonkzero404** [comment]
Hi @justadudewhohacks 

Of course, here's the image

![image_1](https://user-images.githubusercontent.com/5472701/40547848-320a37da-605d-11e8-9918-70e7dec7f47e.jpg)

and then here's my simple example:

```
const cv = require('opencv4nodejs')
const fr = require('face-recognition').withCv(cv)

const detector = fr.FaceDetector()

const mat = cv.imread('./image_1.jpg')
let newMat = mat

const minPxSize = 400000
if ((mat.cols * mat.rows) < minPxSize) {
  console.log('kecil')
  newMat = mat.rescale(minPxSize / (mat.cols * mat.rows))
}

const cvImg = fr.CvImage(newMat)

console.log('detecting faces')
const faceRects = detector.locateFaces(cvImg)

const faces = faceRects
  .map(mmodRect => fr.toCvRect(mmodRect.rect))
  .map(cvRect => mat.getRegion(cvRect).resize(150, 150))

faces.forEach((face, i) => {
  cv.imshow(`face_${i}`, face)
})
cv.waitKey()
```
the result:
![screen shot 2018-05-25 at 20 56 09](https://user-images.githubusercontent.com/5472701/40548197-3d5b1982-605e-11e8-842c-55540e53e38b.png)

Thanks.

**Comment by justadudewhohacks** [comment]
Ahh I see, yes `mat.getRegion` will crash if the rect is out of the image bounds. Probably also a good idea to ensure that `x + width < mat.cols ` and  `y + height < mat.rows `.
