### ISSUE TITLE
Face rotation/angle detection

### ISSUE THREAD

**Issue by Chinafreak** [justadudewhohacks/face-recognition.js#95]
It would be nice if there would be a way to detect the face's direction/rotation. You can calculate direction from both eyes.

**Comment by Chinafreak** [comment]
Maybe just getting eyes, nose and mouth position would be enough

**Comment by YanDevDe** [comment]
You can get eye position from Face Landmarks which allows you to calculate to get angle. So solved!

**Comment by gauravdhra** [comment]
Hi @YanDevDe .
I need the same solution. I have been trying to find the solution for 2 weeks. 
Could you please tell me what is that calculation to find if face is looking forward / little up  or not ?

I need that solution to find out multiple faces out from a video of student class room. 
![image](https://user-images.githubusercontent.com/40135431/93591725-85b48180-f9ce-11ea-9795-39dd96731082.png)

**Comment by YanDevDe** [comment]
Hello @gauravdhra 
It was 2 years ago, so I might have forgotten how to solve it. Sorry!
But I'll try my best here:

I assume you can get position by using [face landmark](https://github.com/justadudewhohacks/face-recognition.js#face-landmarks).

With those position you can either calculate...

- the face rotations (by using both eye positions, [this trick should works](https://gist.github.com/conorbuck/2606166))
- tilting face (up/down) by calculating the distance between both eyes and mouth/nose position. The shorter distance it is, the more you're looking down/up. [To calculate distance between two points, you can check it out here](https://stackoverflow.com/questions/20916953/get-distance-between-two-points-in-canvas)

I'm sorry if I was not a help!

Regards,

Yan

**Comment by YanDevDe** [comment]
Also you may want to checkout at [face-api.js](https://github.com/justadudewhohacks/face-api.js) since this face-recognition.js is obsolete.

**Comment by gauravdhra** [comment]
Hey @YanDevDe  ,after two years you still have solution wow !!!

I have all the position let me find the value of **c** :)

eye_right  **[466.1014111340046, 199.98082201182842]**
eye_left  **[446.8404211352269, 199.97677264114222]**
nose  **[455.0013075934516, 208.0722832745976]**
mouth **[456.26030165702105, 215.79589595198632]**

**Comment by YanDevDe** [comment]
@gauravdhra to be fair, I forgot that I was using this library lol. But this was a logical approach to detect the rotation/tilt of the faces.

Yeah those values are more than enough! Now calculating is the only part left! =)

Glad that I could help you!

Regards, Yan

**Comment by gauravdhra** [comment]
@YanDevDe 

Could you clarify this **The shorter distance it is, the more you're looking down/up** .
how to know if distance is shorter or not ? I am confused :p
shorter distance > looking down 


![image](https://user-images.githubusercontent.com/40135431/93594879-4ab54c80-f9d4-11ea-94e1-ee7fb368eb55.png)

**Comment by gauravdhra** [comment]
the distance between both eyes should be equal to the distance between any eye and mouth .
it they are not equal or the smaller one  then its looking  down ..
am I right

**Comment by YanDevDe** [comment]
You can either calculate the center point (lets call `cp`) between both eyes. (Or if you want to be lazy, just use left or right eye position, but it would be better to get center point between both of the eyes for more accurate result)

For mouth position, let's call `mp`.

So that means in order to calculate the `distance` between eyes and mouth position, you need to do that:

```js
const distance_x = mp.x - cp.x;
const distance_y = mp.y - cp.y;
const distance = Math.sqrt(distance_x * distance_x + distance_y + distance_y); 
```

The distance is now the value which you can guess if the face is tilting or not. The smaller distance it is, the more you're looking down or looking up (by up, I mean like up and not front)

The distance value may be bit different depending on face's different position / distances. So using simple equal operator may be not enough. But that's up to you to solve it. 😅

**Comment by gauravdhra** [comment]
@YanDevDe  I understand the distance will be calculated according to the close faces and the faces sitting behind .
that is now a difficult part ...oops  

I have calculated the distance and I am stuck here how to decide the face rotation

**Comment by YanDevDe** [comment]
As far I've read from a while ago, almost every face has same eyes distance (left and right eye). So you can use eyes distance to tell on which distance your face is from camera. 🤷 But don't see this as confirmation, maybe I'm wrong as well.

You can also use the rectangle detection sizes as distance between face and camera, if that works for you.

**Comment by gauravdhra** [comment]
Hi @YanDevDe  that was helpful for me .
Now I need to find if face is not turned to left or right .I need straight looking faces .

**Comment by gauravdhra** [comment]
@YanDevDe Please help me out 
See some face are looking down but it still detecting it .So for the improvement little bit I want to find bottom looking side faces/ or just side faces that will be enough  .
![image](https://user-images.githubusercontent.com/40135431/94689364-6ad9f980-034c-11eb-97ac-0f3841a1af78.png)

**Comment by trongmanh19** [comment]
Hi @YanDevDe @gauravdhra,  Please help me
I get position of mouth, left eye and right eye by blow code
`
const landmarks = await faceapi.detectFaceLandmarks(videoEl);
      const mouth = landmarks.getMouth();

      const leftEye = landmarks.getLeftEye();

      const rightEye = landmarks.getRightEye();

     console.log("Mouth position ===>" + JSON.stringify(mouth));

      console.log("Left eye position ===>" + JSON.stringify(leftEye));

      console.log("Right eye position ===>" + JSON.stringify(rightEye));

 `
Result:
`
```
// mouth position
[{"_x":203.203125,"_y":399.6875},{"_x":217.1484375,"_y":382.5},{"_x":230.7421875,"_y":383.4375},{"_x":245.625,"_y":376.5625},{"_x":254.296875,"_y":370.3125},{"_x":253.828125,"_y":365},{"_x":275.859375,"_y":371.875},{"_x":275.625,"_y":360.625},{"_x":283.125,"_y":396.875},{"_x":267.1874713897705,"_y":420.00003814697266},{"_x":258.28125,"_y":424.6875},{"_x":238.2421875,"_y":415.3125},{"_x":202.14845180511475,"_y":399.6875},{"_x":236.015625,"_y":381.5625},{"_x":246.5625,"_y":383.4375},{"_x":258.75,"_y":371.5625},{"_x":264.140625,"_y":366.5625},{"_x":269.296875,"_y":390.3125},{"_x":259.21875,"_y":405.9375},{"_x":252.1875,"_y":406.875}]

// leftEye position
[{"_x":98.14453125,"_y":344.0625},{"_x":106.99220180511475,"_y":331.875},{"_x":126.4453125,"_y":318.28125},{"_x":156.09375,"_y":314.0625},{"_x":140.390625,"_y":329.375},{"_x":112.32422590255737,"_y":333.75}]

// rightEye position
[{"_x":220.3125,"_y":286.7187690734863},{"_x":243.2812786102295,"_y":277.03125},{"_x":247.9687786102295,"_y":283.59375},{"_x":246.796875,"_y":269.0625},{"_x":243.2812786102295,"_y":292.1875},{"_x":243.2812786102295,"_y":286.25}]
```
`
How to calculate distance from left/right eye to mouth?
Thanks!

**Comment by fredzhu008** [comment]
Hi,
&nbsp; &nbsp;Did you have the detailed requirements ?such as pdf. Could you send another email.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "justadudewhohacks/face-recognition.js"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月18日(星期一) 下午5:49
收件人:&nbsp;"justadudewhohacks/face-recognition.js"<face-recognition.js@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [justadudewhohacks/face-recognition.js] Face rotation/angle detection (#95)





 
Hi @YanDevDe @gauravdhra,  Please help me
 I get position of mouth, left eye and right eye by blow code
 const mouth = landmarks.getMouth(); const leftEye = landmarks.getLeftEye(); const rightEye = landmarks.getRightEye(); console.log("Left eye position ===&gt;" + JSON.stringify(leftEye)); console.log("Right eye position ===&gt;" + JSON.stringify(mouth)); console.log("Mouth position ===&gt;" + JSON.stringify(mouth)); 
 Result:
 // mouth position [{"_x":203.203125,"_y":399.6875},{"_x":217.1484375,"_y":382.5},{"_x":230.7421875,"_y":383.4375},{"_x":245.625,"_y":376.5625},{"_x":254.296875,"_y":370.3125},{"_x":253.828125,"_y":365},{"_x":275.859375,"_y":371.875},{"_x":275.625,"_y":360.625},{"_x":283.125,"_y":396.875},{"_x":267.1874713897705,"_y":420.00003814697266},{"_x":258.28125,"_y":424.6875},{"_x":238.2421875,"_y":415.3125},{"_x":202.14845180511475,"_y":399.6875},{"_x":236.015625,"_y":381.5625},{"_x":246.5625,"_y":383.4375},{"_x":258.75,"_y":371.5625},{"_x":264.140625,"_y":366.5625},{"_x":269.296875,"_y":390.3125},{"_x":259.21875,"_y":405.9375},{"_x":252.1875,"_y":406.875}] // leftEye position [{"_x":98.14453125,"_y":344.0625},{"_x":106.99220180511475,"_y":331.875},{"_x":126.4453125,"_y":318.28125},{"_x":156.09375,"_y":314.0625},{"_x":140.390625,"_y":329.375},{"_x":112.32422590255737,"_y":333.75}] // rightEye position [{"_x":220.3125,"_y":286.7187690734863},{"_x":243.2812786102295,"_y":277.03125},{"_x":247.9687786102295,"_y":283.59375},{"_x":246.796875,"_y":269.0625},{"_x":243.2812786102295,"_y":292.1875},{"_x":243.2812786102295,"_y":286.25}]
 How to calculate distance from left/right eye to mouth?
 Thanks!

**Comment by fredzhu008** [comment]
add my weichat 13501901060




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "justadudewhohacks/face-recognition.js"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月18日(星期一) 下午5:49
收件人:&nbsp;"justadudewhohacks/face-recognition.js"<face-recognition.js@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [justadudewhohacks/face-recognition.js] Face rotation/angle detection (#95)





 
Hi @YanDevDe @gauravdhra,  Please help me
 I get position of mouth, left eye and right eye by blow code
 const mouth = landmarks.getMouth(); const leftEye = landmarks.getLeftEye(); const rightEye = landmarks.getRightEye(); console.log("Left eye position ===&gt;" + JSON.stringify(leftEye)); console.log("Right eye position ===&gt;" + JSON.stringify(mouth)); console.log("Mouth position ===&gt;" + JSON.stringify(mouth)); 
 Result:
 // mouth position [{"_x":203.203125,"_y":399.6875},{"_x":217.1484375,"_y":382.5},{"_x":230.7421875,"_y":383.4375},{"_x":245.625,"_y":376.5625},{"_x":254.296875,"_y":370.3125},{"_x":253.828125,"_y":365},{"_x":275.859375,"_y":371.875},{"_x":275.625,"_y":360.625},{"_x":283.125,"_y":396.875},{"_x":267.1874713897705,"_y":420.00003814697266},{"_x":258.28125,"_y":424.6875},{"_x":238.2421875,"_y":415.3125},{"_x":202.14845180511475,"_y":399.6875},{"_x":236.015625,"_y":381.5625},{"_x":246.5625,"_y":383.4375},{"_x":258.75,"_y":371.5625},{"_x":264.140625,"_y":366.5625},{"_x":269.296875,"_y":390.3125},{"_x":259.21875,"_y":405.9375},{"_x":252.1875,"_y":406.875}] // leftEye position [{"_x":98.14453125,"_y":344.0625},{"_x":106.99220180511475,"_y":331.875},{"_x":126.4453125,"_y":318.28125},{"_x":156.09375,"_y":314.0625},{"_x":140.390625,"_y":329.375},{"_x":112.32422590255737,"_y":333.75}] // rightEye position [{"_x":220.3125,"_y":286.7187690734863},{"_x":243.2812786102295,"_y":277.03125},{"_x":247.9687786102295,"_y":283.59375},{"_x":246.796875,"_y":269.0625},{"_x":243.2812786102295,"_y":292.1875},{"_x":243.2812786102295,"_y":286.25}]
 How to calculate distance from left/right eye to mouth?
 Thanks!

**Comment by trongmanh19** [comment]
@fredzhu008 I need to find if face is turned to left or right or straight looking faces.
Can you help me?

**Comment by fredzhu008** [comment]
Could you send the original project description or other indormation,or example for that draw by handwriting?
I cannot get the goal for this project. It's you lab practice or commercial project?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "justadudewhohacks/face-recognition.js"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月21日(星期四) 上午10:17
收件人:&nbsp;"justadudewhohacks/face-recognition.js"<face-recognition.js@noreply.github.com&gt;;
抄送:&nbsp;"Fred"<401450070@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [justadudewhohacks/face-recognition.js] Face rotation/angle detection (#95)





 
@fredzhu008 I need to find if face is turned to left or right or straight looking faces.
 Can you help me?
