### ISSUE TITLE
Convert detected face to base64

### ISSUE THREAD

**Issue by Zaftri** [justadudewhohacks/face-recognition.js#96]
Hi guys, i'm trying to write api that recive image, detect face, then return as string in base64. I tried to find functions in face-recognition, but without a luck. Do you have/know any solution for that?

**Comment by justadudewhohacks** [comment]
There is no built in function in this package to convert images from or to base64. However you can do all that by using this package in conjunction with [opencv4nodejs](https://github.com/justadudewhohacks/opencv4nodejs). If it's only about face detection and not face recognition, you could probably also simply use the CascadeClassifer in opencv4nodejs for detection with haar cascades.

**Comment by Zaftri** [comment]
Thank you for your answer. I'm creating app that will store detected faces in database and use it for learning, online. Can you point me a direction where i should look in opencv4nodejs for functions that would convert detected faces to base64?

**Comment by justadudewhohacks** [comment]
You could simply compute the coordinates of the bounding boxes for the faces, with the face detector and extract the face images with opencv4nodejs `mat.getRegion(x, y, width, height)`. To encode a `cv.Mat` to a base64 string simply use `cv.imencode(mat)`
