### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by LBRGeorge** [justadudewhohacks/face-recognition.js#99]
I'm trying to install the package but I got the following error:

`LINK : fatal error LNK1194: cannot delay-load 'node.exe' due to import of data symbol '"__declspec(dllimport) const std::basic_ostream<char,struct std::char_traits<char> >::vftable'" (__imp_??_7?$basic_ostream@DU?$char_traits@D@std@@@std@@6B@)'; link without /DELAYLOAD:node.exe [D:\Projects\friday\node_modules\face-recognition\build\facerec.vcxproj]`

**NodeJS: 10.4.1
NPM: 6.1.0
OS: Windows 10 Pro 64bits Build 17134**

**Comment by justadudewhohacks** [comment]
Hmm seems to be an issue with nodejs 10. I will have to investigate in this, maybe due to outdated dependencies.

For now simply use node 9.

**Comment by justadudewhohacks** [comment]
Should be fixed now. You can try again with the latest version on npm.

**Comment by LBRGeorge** [comment]
It worked perfectly!
Thank you!
